namespace WorldCup.Engine.Simulation;

using WorldCup.Engine.Random;

/// <summary>
/// Play-by-play announcer phrase catalogue for goal events. Each pool is a flat
/// array of spoken commentary fragments containing NO player names, team names or
/// scores — the caller layers those in around the chosen fragment.
/// </summary>
public static partial class CommentaryPhrases
{
    // ---------------------------------------------------------------------
    // GoalShout pools — three excitement tiers.
    // ---------------------------------------------------------------------

    private static readonly string[] GoalShoutsScreamer =
    {
        "OHHH WHAT A GOAL!!!",
        "ARE YOU KIDDING ME?!",
        "WRITE THAT ONE INTO FOLKLORE!",
        "ABSOLUTELY UNBELIEVABLE!!!",
        "OH YOU BEAUTY!!!",
        "GET IN THERE!!!",
        "WHAT ON EARTH HAVE WE JUST SEEN?!",
        "THAT IS SENSATIONAL!!!",
        "I DON'T BELIEVE IT!!!",
        "STOP EVERYTHING — LOOK AT THAT!!!",
        "HE'S DONE IT AGAIN!!!",
        "A GOAL FOR THE AGES!!!",
        "OH MY WORD, WHAT A HIT!!!",
        "THAT'S GONE INTO THE TOP CORNER LIKE A MISSILE!!!",
        "PINCH YOURSELF, THAT WAS REAL!!!",
        "SCREAMER!!! ABSOLUTE SCREAMER!!!",
        "THE ROOF OF THE NET IS STILL SHAKING!!!",
        "WORLD CLASS! WORLD CLASS! WORLD CLASS!!!",
        "OH, THIS IS MAGNIFICENT!!!",
        "TELL ME THAT DIDN'T JUST HAPPEN!!!",
        "BREATHTAKING! SIMPLY BREATHTAKING!!!",
        "FRAME IT AND HANG IT ON THE WALL!!!",
        "GOAL OF THE TOURNAMENT, SURELY!!!",
        "HE'S RIPPED IT INTO THE ROOF OF THE NET!!!",
        "OH, THAT IS DELICIOUS!!!",
        "WHAT A MOMENT, WHAT A GOAL!!!",
        "THE CROWD ARE ON THEIR FEET — AND SO AM I!!!",
        "UTTERLY, UTTERLY SPECTACULAR!!!",
        "THAT'S THE GREATEST GOAL I'VE SEEN IN YEARS!!!",
        "POETRY! ABSOLUTE POETRY!!!",
        "HE HAS LOST HIS MIND AND SO HAVE I!!!",
        "OH, GIVE THAT MAN A STANDING OVATION!!!",
        "THUNDERBOLT!!! AN ABSOLUTE THUNDERBOLT!!!",
        "THAT WILL BE REPLAYED FOR A HUNDRED YEARS!!!",
        "MY GOODNESS, WHAT A FINISH!!!",
        "THE STADIUM HAS ERUPTED!!!",
        "JUST WHEN YOU THOUGHT YOU'D SEEN IT ALL!!!",
        "OH, HE'S A GENIUS, A PURE GENIUS!!!",
        "THAT IS THE GOAL OF THE CENTURY!!!",
        "NOBODY IN THE STADIUM CAN BELIEVE WHAT THEY JUST SAW!!!",
        "HE HAS JUST REWRITTEN THE HISTORY BOOKS!!!",
        "A MOMENT THAT WILL LIVE FOREVER!!!",
        "TURN THE CAMERAS OFF — NOTHING WILL TOP THAT!!!",
        "THE KEEPER DIDN'T EVEN MOVE — IT WAS UNSTOPPABLE!!!",
        "THEY WILL STILL BE TALKING ABOUT THAT IN FIFTY YEARS!!!",
        "MAJESTIC!!! ABSOLUTELY MAJESTIC!!!",
        "HE'S PUT IT IN ORBIT AND BROUGHT IT BACK!!!",
        "OH, THE AUDACITY!!! THE SHEER AUDACITY!!!",
        "THAT IS FOOTBALL IN ITS PUREST, MOST GLORIOUS FORM!!!",
        "HE PICKED HIS SPOT AND HIT IT PERFECTLY — INCREDIBLE!!!",
        "EVERY SINGLE PERSON IN THIS STADIUM IS ON THEIR FEET!!!",
        "THAT BALL IS STILL MOVING AND THE NET HAS ALREADY BURST!!!",
        "JUST LOOK AT THE TRAJECTORY ON THAT!!!",
        "A THUNDERCLAP!!! AN ABSOLUTE THUNDERCLAP!!!",
        "TEARS IN THE STANDS — AND I UNDERSTAND WHY!!!",
        "HE'S DONE SOMETHING NO ONE THOUGHT POSSIBLE!!!",
        "SEND FOR THE TROPHY — SURELY THIS IS IT!!!",
        "THAT KEEPER NEVER HAD A PRAYER!!!",
        "THE DEFINITION OF A WORLDIE!!!",
        "I AM SPEECHLESS!!! ABSOLUTELY SPEECHLESS!!!",
        "WHAT A TIME TO BE ALIVE!!!",
        "HE SHAPED UP AND JUST UNLEASHED IT!!!",
    };

    private static readonly string[] GoalShoutsExcited =
    {
        "That is a wonderful goal!",
        "He's buried it!",
        "What a strike!",
        "Oh, that's a lovely finish!",
        "Brilliantly taken!",
        "He's made no mistake there!",
        "A superb goal!",
        "That's a beauty!",
        "He's tucked that away in style!",
        "What composure, what a finish!",
        "Marvellous work, and it's in!",
        "He's lashed it home!",
        "A terrific finish!",
        "That's a goal of real quality!",
        "He's slotted it beautifully!",
        "Oh, that's well struck!",
        "He's picked his spot perfectly!",
        "A fine, fine goal!",
        "Clinically done!",
        "He's smashed it in!",
        "What a way to take it!",
        "That's a cracker!",
        "He's drilled it low and hard!",
        "Top-class finishing!",
        "He's curled it home gorgeously!",
        "A real collector's item!",
        "That's beautifully executed!",
        "He's rifled it past the keeper!",
        "What a delightful goal!",
        "He's finished with aplomb!",
        "Oh, that's classy!",
        "He's planted it in the corner!",
        "A goal to savour!",
        "He's made that look easy!",
        "Sumptuous, just sumptuous!",
        "He's thumped it into the net!",
        "That's a smashing goal!",
        "He's nicked it past the keeper beautifully!",
        "An outstanding finish — the keeper had no chance!",
        "He's arrowed it into the corner!",
        "Clinical, absolutely clinical!",
        "He's stroked it home with real class!",
        "Oh, what a hit, what a hit!",
        "He's curled it into the far corner magnificently!",
        "He's whipped it in and it's gone straight in!",
        "There's real quality in that finish!",
        "He's bended it and it's gone in off the post!",
        "He's swept it low and hard — no chance for the keeper!",
        "A beautiful, flowing finish!",
        "He's volleyed that home superbly!",
        "He took his time, picked his spot, and delivered!",
        "That's a world-class finish from a world-class player!",
        "He's shaped up and struck it sweetly!",
        "A real poacher's instinct, and a fine finish to match!",
        "He's threaded it through the narrowest of gaps!",
        "What poise, what composure — and what a goal!",
        "He's rattled it into the roof of the net!",
        "A clever, deft finish — beautifully done!",
        "He's dinked it over the keeper with impudent skill!",
        "What technique! What an absolutely wonderful goal!",
        "He's found the bottom corner with unerring accuracy!",
        "He's kept his head and found the net — brilliant!",
        "A dipping, skidding finish that the keeper had no read on!",
        "He's lashed that one home in emphatic fashion!",
        "That's a header of real authority — thundered in!",
    };

    private static readonly string[] GoalShoutsRoutine =
    {
        "It's in!",
        "He scores!",
        "Tucked away.",
        "And that's a goal.",
        "He gets it.",
        "In the back of the net.",
        "That'll do the job.",
        "A goal, and a deserved one.",
        "He makes it count.",
        "Simple as you like.",
        "He puts it away.",
        "There it is.",
        "Job done.",
        "He finds the net.",
        "It nestles in the corner.",
        "He slots it home.",
        "That's gone in.",
        "He converts.",
        "And the keeper had no chance.",
        "It crosses the line.",
        "He buries the chance.",
        "Clean finish.",
        "He makes no mistake.",
        "Goal.",
        "He takes it well enough.",
        "That's a routine finish.",
        "Into the net it goes.",
        "He gets his reward.",
        "He sweeps it in.",
        "Calmly taken.",
        "A tidy finish.",
        "He pops it in.",
        "That'll count.",
        "He gets on the scoresheet.",
        "It finds its way home.",
        "He prods it over the line.",
        "A goal to show for it.",
        "Right place, right time.",
        "He steers it home.",
        "He pounces, and it's in.",
        "A smart finish, nothing more needed.",
        "He's on the scoresheet.",
        "A straightforward conversion.",
        "He gets a touch and it's over the line.",
        "He clips it in.",
        "A deserved goal.",
        "Bundled in.",
        "He scrambles it over the line.",
        "The keeper had no chance from there.",
        "He takes his chance.",
        "A well-taken goal.",
        "He plants it in and wheels away.",
        "A clean strike — nothing spectacular, but it counts.",
        "He rolls it home with his weaker foot.",
        "He picks up the pieces and tucks it away.",
        "A composed, measured finish.",
        "He didn't need to be spectacular — he just needed to score.",
        "He swings a leg and finds the net.",
        "He wraps his foot round it and it goes in.",
        "Unhurried, controlled, effective.",
        "He finishes it at the second attempt.",
        "A headed nod over the line.",
        "He squeezes it just inside the upright.",
    };

    // ---------------------------------------------------------------------
    // GoalDescriptor pools — routine + elaborate per GoalType (OwnGoal: single).
    // ---------------------------------------------------------------------

    private static readonly string[] DescOpenPlayRoutine =
    {
        "a tidy finish from inside the box",
        "a simple tap-in",
        "a composed side-footed effort",
        "a sharp finish at the near post",
        "a close-range conversion",
        "a routine strike from open play",
        "a low drive into the corner",
        "a first-time finish",
        "a poke home from a yard out",
        "a calm finish past the keeper",
        "a smart turn and shot",
        "a one-on-one finish",
        "a tucked-away chance",
        "a finish on the half-volley",
        "a guided effort into the net",
        "a prod home from the six-yard box",
        "a controlled strike from the edge of the area",
        "a clean strike through the keeper's legs",
        "a neat finish across goal",
        "a placed shot into the bottom corner",
        "a tap-in at the back post",
        "a scuffed but effective finish",
        "a quick snapshot from inside the box",
        "a measured finish under the keeper",
        "a poacher's strike",
        "a rebound bundled over the line",
        "a stooping effort from close in",
        "a swept finish into the side netting",
        "a toe-poke past the goalkeeper",
        "a simple slot into an open net",
        "a close-range header turned in",
        "a tidy right-footed finish",
        "a tidy left-footed finish",
        "a comfortable conversion from the spot of the action",
        "a clipped finish over the advancing keeper",
        "a finish squeezed in at the near post",
        "a deft toe-poke from close range",
        "a bundled effort forced over the line",
        "a fortunate ricochet turned in",
        "a chested-down and volleyed effort",
        "a sharp turn and low finish",
        "a composed one-on-one with the goalkeeper",
        "a clipped finish to the far post",
        "a short-range header nodded across the line",
        "a neat backheel into the path of an onrushing teammate, then finished",
        "a one-touch flick from inside the six-yard box",
        "a slid finish across the keeper's body",
        "a striker's header steered firmly down",
        "an instinctive poke with the trailing foot",
        "a scrambled finish from a yard out",
        "a measured low shot rolled into the corner",
        "a smart flick-on converted at the back post",
        "a cool side-footed finish from inside the area",
        "a driven half-volley from inside the box",
        "a clinical right-footed finish on the turn",
        "a neat chest control and tidy finish",
        "a well-read rebound snap-shot",
        "a penalty-box finish after a neat one-two",
        "a thumping downward header from the near post",
        "a quick-fire finish off the inside of the post",
    };

    private static readonly string[] DescOpenPlayElaborate =
    {
        "a mazy run and finish",
        "a sublime piece of individual brilliance",
        "a jinking, weaving solo goal",
        "a breathtaking team move finished in style",
        "a dazzling dribble and clinical strike",
        "an exquisite first-time finish on the run",
        "a stunning curling effort into the top corner",
        "a glorious dink over the onrushing keeper",
        "a magnificent finish after a flowing move",
        "an audacious chipped finish",
        "a wonderfully disguised side-footed strike",
        "a thunderous half-volley into the roof of the net",
        "a sensational solo charge through the defence",
        "a beautifully weighted finish into the far corner",
        "a moment of sheer footballing genius",
        "a perfectly timed run and ruthless finish",
        "a swerving, dipping strike that left the keeper rooted",
        "an outrageous flick and finish",
        "a delightful one-two and clinical conversion",
        "a sumptuous curled effort beyond the dive",
        "a rasping drive arrowed into the corner",
        "a balletic turn and unstoppable shot",
        "a venomous strike on the swivel",
        "a gorgeous bending finish around the defender",
        "a slaloming run past three defenders and a finish",
        "a majestic lofted finish into the top bins",
        "a ferocious effort that nearly burst the net",
        "an instinctive, acrobatic finish",
        "a coolly dispatched finish after a mesmerising run",
        "a thunderbolt struck on the half-turn",
        "a piece of magic conjured from nothing",
        "a flowing, end-to-end move finished emphatically",
        "an extravagant back-heeled finish",
        "a scorching effort drilled into the bottom corner",
        "a beautifully crafted goal from a sweeping counter",
        "a stunning strike that arrowed past the helpless keeper",
        "a scintillating team move finished in the most emphatic fashion",
        "a first-time volley crashed emphatically into the roof of the net",
        "a dazzling run from deep and a clinical, unstoppable finish",
        "a flowing counter-attack swept home with devastating pace and power",
        "an outrageous rabona finish that left the crowd in disbelief",
        "a perfectly weighted chip that floated delicately over the keeper",
        "a defence-splitting one-two and a ruthless clinical finish",
        "a searing burst of pace and a lethal low drive into the corner",
        "an improvised, acrobatic finish from an impossible angle",
        "a sweeping move spanning the width of the pitch, finished gloriously",
        "a thumping strike off the underside of the bar and in",
        "a disguised finish, the keeper sold a dummy and beaten at the near post",
        "a powerful surge forward and a ferocious finish from the edge of the area",
        "an intelligent run behind the defence and a perfectly placed strike",
        "a clinical low finish into the bottom corner after a searing break",
        "a brilliantly crafted goal from a patient, relentless team move",
        "a backheel flick into the path of the run, and a superb finish beyond",
        "a thumping headed finish from a perfectly flighted delivery",
        "a goal that showcased every weapon in a world-class footballer's arsenal",
        "a jinking run through a forest of legs and a stunning finish",
        "a driven cross-shot into the far corner that deceived everyone",
        "a spin on the ball, two defenders left on the floor, and a clinical finish",
        "an outswinging delivery converted with a thunderous near-post header",
        "a blistering one-touch passing move finished with the outside of the boot",
    };

    private static readonly string[] DescHeaderRoutine =
    {
        "a header from close range",
        "a nodded finish at the near post",
        "a glancing header into the corner",
        "a downward header past the keeper",
        "a header from the six-yard box",
        "a firm header into the net",
        "a guided header inside the post",
        "a header from a corner",
        "a stooping header at the back post",
        "a header steered home",
        "a header nodded over the line",
        "a header from the centre of the box",
        "a header flicked goalwards",
        "a header met cleanly at the front post",
        "a header bundled in",
        "a routine header from a set-piece",
        "a header planted into the ground and up",
        "a header off the underside of the bar and in",
        "a header from a pinpoint cross",
        "a back-post header tucked away",
        "a header nodded across the keeper",
        "a header rising to meet the delivery",
        "a near-post header turned in",
        "a header looped over the goalkeeper",
        "a header dispatched from a free-kick delivery",
        "a header met under little pressure",
        "a header from a deep cross",
        "a header steered into the bottom corner",
        "a header glanced on and in",
        "a header buried from a yard out",
        "a header nodded down into the net",
        "a simple header at the far post",
        "a header from a whipped delivery",
        "a header thumped into the floor and up over the line",
        "a header directed firmly past the keeper",
        "a header met flush at the near upright",
        "a header redirected cleverly past the keeper",
        "a flicked near-post header to the far corner",
        "a brave, committed header despite the challenge",
        "a header from a driven corner met at the six-yard box",
        "a header directed into the bottom corner from a flick-on",
        "a corner delivered to the back post and nodded in",
        "a header off the line of the cross at full stretch",
        "a downward header from a whipped delivery",
        "a header powered in from the penalty spot",
        "a header diverted in from a set-piece routine",
        "a smart header at the front post, flicked goalwards",
        "a header met firmly from a deep free-kick delivery",
        "a header rising above the pack and directed home",
        "a scrappy header bundled over the line under pressure",
        "a header from a late run into the box, timing impeccable",
        "a header steered goalwards from a chipped ball over the top",
        "a deft header back across the keeper from the byline",
        "a header glanced goalwards off the top of the skull",
        "a header flung forward from a goal kick delivered long",
    };

    private static readonly string[] DescHeaderElaborate =
    {
        "a towering header",
        "a thumping header that left the keeper helpless",
        "a soaring leap and powerful header",
        "an emphatic header crashed into the net",
        "a magnificent header rising above the defence",
        "a bullet header into the top corner",
        "a thunderous downward header",
        "a spectacular header from a towering jump",
        "a commanding header that flew past the keeper",
        "a header of immense power and precision",
        "a glorious looping header over the stranded keeper",
        "a header met with unstoppable force",
        "a header hung in the air before being dispatched",
        "a brave diving header at full stretch",
        "a header thundered in from a leap of remarkable height",
        "a header guided perfectly into the far corner with the flight defied",
        "a header that arrowed in off the underside of the crossbar",
        "a stooping diving header that defied the angle",
        "a header hammered home above a crowd of bodies",
        "a header met flush and rifled into the roof of the net",
        "a header of real authority into the bottom corner",
        "a header rising majestically to bury the cross",
        "a header met with venom at the back post",
        "a header that flew like a shot into the corner",
        "a header crashed in after climbing above two markers",
        "a header sent looping unstoppably beyond the keeper's reach",
        "a header dispatched with the timing of a born goalscorer",
        "a header thumped down and bouncing up into the net",
        "a header drilled in with astonishing power",
        "a header met at the perfect moment and buried",
        "a header that screamed into the top corner",
        "a header of breathtaking elevation and accuracy",
        "a header smashed home from an outrageous hang-time",
        "a header steered devastatingly across the keeper",
        "a header met with such force the net nearly tore",
        "a header of pure aerial dominance",
        "a diving header flung full-length to reach the cross",
        "a leaping header from the back of the area — astonishing power",
        "a header hammered down from a towering height",
        "a bullet header from a corner delivered at pace",
        "a header lashed emphatically into the side netting",
        "a header that seemed to gain pace as it flew in",
        "a header struck with the timing of a born goalscorer",
        "a magnificent looping header from a tight angle",
        "a header from a free-kick swung in behind the wall",
        "a header of devastating force from the six-yard line",
        "a header dispatched with one hand on the face of the defender",
        "a glancing header deflected perfectly into the far post",
        "a header won in a physical duel and emphatically buried",
        "a flicked overhead header of stunning improvisation",
        "a header angled low, leaving the keeper rooted to the spot",
        "a powerful header driven in from a flick at the near post",
        "a header met with the crown of the skull and arrowed in",
    };

    private static readonly string[] DescFreeKickRoutine =
    {
        "a well-struck free-kick",
        "a free-kick into the corner",
        "a low free-kick under the wall",
        "a free-kick guided past the wall",
        "a free-kick driven goalwards",
        "a free-kick clipped into the net",
        "a free-kick beyond the goalkeeper",
        "a free-kick squeezed inside the post",
        "a free-kick whipped towards goal",
        "a free-kick placed into the side netting",
        "a free-kick struck cleanly home",
        "a free-kick threaded past the wall",
        "a free-kick deflected in off the wall",
        "a free-kick swung into the danger area and in",
        "a free-kick rolled under the jumping wall",
        "a free-kick directed into the bottom corner",
        "a free-kick that beat the keeper at his near post",
        "a free-kick curled around the defenders",
        "a free-kick that found the gap in the wall",
        "a free-kick struck low and true",
        "a free-kick tucked inside the upright",
        "a free-kick drilled towards the bottom corner",
        "a free-kick floated in and converted",
        "a free-kick steered home from the edge of the box",
        "a free-kick that crept inside the post",
        "a free-kick fired through a gap",
        "a free-kick lifted over the wall and in",
        "a free-kick taken quickly and finished",
        "a free-kick stroked into the corner",
        "a free-kick that found the net via a touch",
        "a free-kick angled past the goalkeeper",
        "a free-kick swept towards goal and in",
        "a free-kick aimed at the near post and converted",
        "a free-kick that nestled inside the far post",
        "a free-kick punched home from range",
        "a free-kick threaded into the bottom corner",
        "a free-kick clipped just over the jumping wall and in",
        "a free-kick dipping late to beat the keeper at full stretch",
        "a free-kick swung in directly and met on the line",
        "a free-kick driven hard and low around the outside of the wall",
        "a free-kick disguised at the last second and redirected in",
        "a free-kick knuckled goalwards with tremendous dip",
        "a quick free-kick that caught the defence completely off guard",
        "a free-kick lofted to the far post and converted",
        "a free-kick shaped away from the wall and in at the far post",
        "a free-kick that crept under the diving keeper",
        "a free-kick bent inward from wide on the right flank",
        "a free-kick taken with a short pass, overlapping run and a finish",
        "a free-kick struck through a gap in the wall along the ground",
        "a floated free-kick at the near post, flicked goalwards",
        "a free-kick delivered to the back stick and met emphatically",
        "a free-kick hit straight and true, keeper unsighted through the wall",
        "a free-kick nudged off in an unexpected direction and tucked in",
    };

    private static readonly string[] DescFreeKickElaborate =
    {
        "an unstoppable free-kick",
        "a stunning free-kick into the top corner",
        "a magnificent free-kick over the wall",
        "a sensational curling free-kick",
        "a free-kick of pure perfection",
        "a wickedly dipping free-kick",
        "a free-kick that bent gloriously into the corner",
        "a free-kick struck with breathtaking precision",
        "a thunderous free-kick into the roof of the net",
        "a free-kick that swerved viciously beyond the wall",
        "a free-kick whipped unstoppably into the top bins",
        "a free-kick of the very highest class",
        "a free-kick that dipped and curled out of the keeper's reach",
        "a free-kick arrowed into the postage stamp",
        "a free-kick of astonishing technique and power",
        "a free-kick bent around the wall and into the corner",
        "a free-kick struck so sweetly it never looked like missing",
        "a free-kick that defied physics on its way in",
        "a free-kick smashed into the top corner with venom",
        "a free-kick curled exquisitely over the despairing wall",
        "a free-kick of jaw-dropping accuracy",
        "a free-kick that screamed into the upper ninety",
        "a free-kick lashed unstoppably home",
        "a free-kick that left the keeper grasping at air",
        "a free-kick of sublime curve and dip",
        "a free-kick rifled into the only gap available",
        "a free-kick struck with the outside of the boot and bent in",
        "a free-kick that flew like an arrow into the corner",
        "a free-kick of mesmerising trajectory",
        "a free-kick dispatched with ruthless brilliance",
        "a free-kick that whistled into the top corner",
        "a free-kick of outrageous quality from distance",
        "a free-kick bent and dipped beyond all reach",
        "a free-kick hammered unstoppably over the wall",
        "a free-kick that nestled in the top corner like a dream",
        "a free-kick of breathtaking technique into the far angle",
        "a free-kick hooked around the wall with the outside of the boot",
        "a free-kick that swerved one way and then the other before finding the net",
        "a free-kick delivered at ferocious pace into the top corner",
        "a free-kick curled around the outside of the wall and in off the post",
        "a free-kick of such precision the wall was entirely irrelevant",
        "a free-kick that dipped at the last moment to beat a stranded keeper",
        "a free-kick struck with the outside of the right boot and shaped in",
        "a free-kick sent like a tracer bullet into the upper corner",
        "a free-kick that left the commentary box in stunned silence",
        "a free-kick delivered with incredible whip and bend in equal measure",
        "a wonderfully inventive free-kick routine finished with a clinical strike",
        "a free-kick arrowed into the gap between keeper and upright",
        "a free-kick of jaw-dropping curl and velocity from long range",
        "a free-kick sent in on a perfectly disguised flight path",
        "a free-kick struck left-footed around the wall and into the far corner",
        "a free-kick of extraordinary technique hit almost off the shin bone",
        "a free-kick that clipped the inside of the post and rolled in",
    };

    private static readonly string[] DescPenaltyRoutine =
    {
        "a clinical penalty",
        "a confident penalty into the corner",
        "a coolly taken spot-kick",
        "a penalty sent the wrong way",
        "a penalty drilled down the middle",
        "a penalty tucked into the corner",
        "a penalty struck firmly home",
        "a penalty placed beyond the keeper",
        "a penalty slotted into the bottom corner",
        "a penalty dispatched with ease",
        "a penalty rolled into the net",
        "a penalty hammered home from the spot",
        "a penalty sent into the opposite corner",
        "a penalty calmly converted",
        "a penalty driven into the roof of the net",
        "a penalty stroked into the corner",
        "a penalty that fooled the goalkeeper",
        "a penalty buried with conviction",
        "a penalty steered low and hard",
        "a penalty side-footed past the keeper",
        "a penalty smashed straight down the centre",
        "a penalty planted into the bottom corner",
        "a penalty taken with nerveless composure",
        "a penalty sent high into the net",
        "a penalty placed just inside the post",
        "a penalty thumped into the corner",
        "a penalty dispatched without fuss",
        "a penalty rifled past the dive",
        "a penalty rolled coolly into the side netting",
        "a penalty converted with assurance",
        "a penalty struck cleanly into the corner",
        "a penalty sent the keeper the wrong way entirely",
        "a penalty hit hard and true",
        "a penalty tucked away from twelve yards",
        "a penalty slammed into the top corner",
        "a penalty finished with total confidence",
        "a penalty dinked off the inside of the post and in",
        "a penalty cracked at height with tremendous force",
        "a penalty stroked calmly to the keeper's right",
        "a penalty sent to the left, keeper went right",
        "a penalty fired hard and low into the corner",
        "a penalty placed with surgical care into the bottom left",
        "a penalty powered home as the keeper guessed wrong",
        "a penalty knocked in off the post",
        "a penalty slammed low and true into the corner of the net",
        "a penalty struck cleanly with the instep, no hesitation",
        "a penalty guided confidently to the keeper's weak side",
        "a penalty driven hard enough to beat any keeper",
        "a penalty waited on, then steered calmly home",
        "a penalty directed high to the keeper's right",
        "a penalty taken at pace and converted first time",
        "a penalty chipped softly into the centre as the keeper committed",
    };

    private static readonly string[] DescPenaltyElaborate =
    {
        "an audacious Panenka down the middle",
        "an ice-cool penalty into the top corner",
        "a penalty of nerveless brilliance",
        "a penalty dispatched with breathtaking composure",
        "a cheeky chipped penalty straight down the middle",
        "a penalty struck with unanswerable power into the corner",
        "a penalty sent emphatically into the roof of the net",
        "a penalty of supreme confidence under enormous pressure",
        "a penalty that screamed into the top corner",
        "a penalty drilled unstoppably into the bottom corner",
        "a penalty taken with the swagger of a master",
        "a penalty placed with surgical precision",
        "a Panenka of outrageous audacity",
        "a penalty smashed into the very top of the net",
        "a penalty struck with such venom the keeper barely moved",
        "a penalty dispatched coolly despite the world watching",
        "a penalty buried with ruthless conviction in the moment of truth",
        "a penalty sent the keeper the wrong way with a glorious dummy",
        "a penalty thumped unerringly into the postage stamp",
        "a penalty of breathtaking nerve from twelve yards",
        "a penalty rolled with insolent calm down the middle",
        "a penalty crashed into the corner beyond any reach",
        "a penalty taken with the cold blood of a born finisher",
        "a penalty lashed unstoppably into the top corner",
        "a penalty of sublime execution under pressure",
        "a penalty chipped delicately as the keeper dived away",
        "a penalty hammered home with magnificent authority",
        "a penalty struck so true it never looked like missing",
        "a penalty of pure ice from the spot",
        "a penalty dispatched with devastating certainty",
        "a penalty that flew into the top corner like a rocket",
        "a penalty converted with astonishing nerve",
        "a penalty placed inch-perfect into the bottom corner",
        "a penalty smashed home in front of a roaring crowd",
        "a penalty of masterful coolness in the cauldron",
        "a penalty sent unstoppably into the side netting",
        "a penalty of breathtaking audacity — an inch-perfect Panenka as the keeper flew",
        "a penalty lashed into the roof of the net with stunning ferocity",
        "a penalty of extraordinary composure in the most pressurised of moments",
        "a penalty dispatched via an outrageous stutter-step and then placed ice-cold",
        "a penalty smashed left-footed across the keeper into the far corner",
        "a penalty delivered with the arrogance of a player who simply knows he will score",
        "a penalty of savage power — the keeper touched it and it still went in",
        "a penalty delivered in the most emphatic fashion imaginable",
        "a penalty curled — yes, curled — into the corner from twelve yards",
        "a penalty executed with a calmness that belied the occasion",
        "a penalty sent into the top corner with the keeper already diving the other way",
        "a penalty of magnificent ruthlessness in the white-hot heat of the moment",
        "a penalty that the keeper guessed right — but couldn't reach",
        "a penalty perfectly placed just inside the post at full stretch height",
        "a penalty struck with such venom it nearly took the netting with it",
        "a penalty rolled into the corner with the insolent ease of a training exercise",
    };

    private static readonly string[] DescLongRangeRoutine =
    {
        "a strike from distance",
        "a long-range effort into the corner",
        "a shot from outside the box",
        "a drive from twenty-five yards",
        "an effort from range that beat the keeper",
        "a low strike from distance",
        "a shot from the edge of the area",
        "a long-range drive into the net",
        "a struck effort from outside the box",
        "a shot from distance that found the corner",
        "a drive from range past the goalkeeper",
        "an effort hit from outside the box",
        "a long shot tucked inside the post",
        "a strike from range into the bottom corner",
        "a shot from outside the area into the net",
        "a powerful effort from distance",
        "a drive from the edge of the box",
        "a shot from twenty-odd yards",
        "a long-range attempt that crept in",
        "an effort from deep that beat the keeper",
        "a shot from range into the side netting",
        "a drive that arrowed in from outside",
        "a strike from distance under the bar",
        "a long shot drilled into the corner",
        "a fizzing effort from range",
        "a low drive from outside the box",
        "a shot from distance that found a gap",
        "a struck effort from the edge of the D",
        "an effort lashed from range",
        "a shot from outside that nestled in the corner",
        "a long-range strike into the bottom corner",
        "a drive hit hard from distance",
        "an effort from range that flew past the keeper",
        "a shot from outside angled into the net",
        "a long-distance effort that found the target",
        "a strike from twenty-five yards into the corner",
        "a long-range pot-shot that caught the keeper off his line",
        "an effort from thirty yards tucked inside the near post",
        "a drive from range that skidded off the turf and in",
        "a dipping shot from outside the box that fell under the bar",
        "a snap-shot from well outside the area that found the corner",
        "an effort struck from distance with the keeper off his line",
        "a shot from the halfway line that left the goalkeeper scrambling",
        "a long-range attempt that deflected off the underside of the crossbar and in",
        "a driven effort from twenty yards that never rose above knee height",
        "a speculative attempt from distance that took a wicked deflection in",
        "a long-range strike hit across the goal and in at the far post",
        "a bending effort from the edge of the D that curved late",
        "an effort from outside the box guided into the bottom corner",
        "a fizzing drive struck from the centre circle that surprised everyone",
        "a low, skidding effort from range the keeper completely misjudged",
        "a measured drive from distance that crept just inside the upright",
    };

    private static readonly string[] DescLongRangeElaborate =
    {
        "a thunderous strike from distance",
        "an unstoppable rocket from thirty yards",
        "a screamer from outside the box",
        "a sensational long-range thunderbolt",
        "a stunning drive into the top corner from range",
        "a piledriver from distance into the roof of the net",
        "a breathtaking effort from fully thirty-five yards",
        "a missile launched from outside the area",
        "a dipping, swerving strike from long range",
        "a ferocious effort that flew in from distance",
        "a long-range bullet into the postage stamp",
        "a stunning curling effort from outside the box",
        "a thunderbolt that arrowed into the top corner",
        "a venomous drive from distance beyond all reach",
        "an outrageous strike from the halfway line",
        "a rasping long-range effort into the upper ninety",
        "a howitzer from twenty-five yards into the corner",
        "a magnificent strike that dipped under the bar from range",
        "a long-range effort of jaw-dropping power",
        "a swerving rocket that left the keeper rooted",
        "a sublime curling strike from well outside the box",
        "a thunderclap of a shot from distance",
        "a stunning effort that screamed into the top corner",
        "a long-range strike of breathtaking technique",
        "a vicious dipping drive from thirty yards",
        "a spectacular effort lashed in from range",
        "a long shot that flew unstoppably into the corner",
        "a wonderstrike from the edge of the centre circle",
        "a colossal hit that nearly tore the net from distance",
        "a long-range effort of astonishing accuracy and power",
        "a thumping drive that whistled into the top corner",
        "a glorious strike arrowed in from twenty-eight yards",
        "an absolute belter from outside the box",
        "a long-range missile into the very top of the net",
        "a scorching effort that bent in from distance",
        "a stunning thunderbolt that lit up the stadium from range",
        "a swerving howitzer from thirty yards that bent away from the keeper at the last",
        "a ferocious piledriver from the edge of the centre circle — sheer audacity",
        "a searing volley on the half-turn from outside the box",
        "a dipping, knuckling drive from long range that the keeper never sighted",
        "a blistering effort with the outside of the boot from thirty yards",
        "a raking drive from well outside the penalty area that never stopped bending",
        "a long-range rocket struck with the laces that nearly broke the net",
        "a swinging long-range effort with wicked late movement past the helpless keeper",
        "a stunning first-time drive from distance — he barely looked and it flew in",
        "a ferocious twenty-five-yarder that pinged off the underside of the bar and in",
        "a rasping half-volley from range that flew into the top corner off the inside of the post",
        "a scorching effort from outside the box struck with the instep at full pace",
        "an unbelievable thirty-five-yard effort — the keeper had it covered until it dipped",
        "a long-range drive that left the keeper rooted to the spot in utter disbelief",
        "a low, skimming rocket from outside the box that cannoned into the bottom corner",
        "a thundering effort from range that flew in off both posts",
    };

    private static readonly string[] DescBicycleKickRoutine =
    {
        "an overhead kick into the net",
        "a bicycle kick from close range",
        "a scissor-kick finish",
        "an overhead effort guided home",
        "a bicycle kick steered past the keeper",
        "an acrobatic overhead finish",
        "a scissor-kick into the corner",
        "an overhead kick tucked away",
        "a bicycle kick directed goalwards",
        "an overhead effort into the bottom corner",
        "a scissor-kick met cleanly and converted",
        "an overhead kick looped over the keeper",
        "a bicycle kick from inside the six-yard box",
        "an overhead finish at the near post",
        "a scissor-kick volleyed home",
        "an overhead kick prodded over the line",
        "a bicycle kick directed into the net",
        "an overhead effort flicked goalwards and in",
        "a scissor-kick guided into the corner",
        "an overhead kick met under pressure and converted",
        "a bicycle kick steered low into the net",
        "an overhead finish from a hanging cross",
        "a scissor-kick struck on the turn and in",
        "an overhead kick nudged past the keeper",
        "a bicycle kick connected and converted",
        "an overhead effort directed into the side netting",
        "a scissor-kick from the edge of the six-yard box",
        "an overhead kick met flush and finished",
        "a bicycle kick steered home from close in",
        "an overhead finish improvised in the box",
        "a scissor-kick volleyed into the corner",
        "an overhead kick directed firmly into the net",
        "a bicycle kick met cleanly and tucked away",
        "an overhead effort guided beyond the goalkeeper",
        "a scissor-kick connected sweetly and converted",
        "an overhead kick steered into the bottom corner",
        "a scissor-kick improvised in a split second and driven home",
        "an overhead kick met flush on the volley under the high ball",
        "a bicycle kick from a corner that looped into the far corner",
        "a scissor-kick flicked goalwards from a low cross",
        "an overhead effort attempted under a high delivery and tucked away",
        "a bicycle kick taken with outstretched leg from just inside the box",
        "an overhead kick at the back post from a floated delivery",
        "a scissor-kick from a deep cross at the front post",
        "a bicycle kick guided across the keeper and into the net",
        "an overhead effort swung at with tremendous improvisation",
        "a scissor-kick met cleanly at the far post and bundled in",
        "an overhead kick from a low, driven cross inside the six-yard box",
        "a bicycle kick met from a square cross across the penalty area",
        "a scissor-kick on the turn from a ball played over the top",
    };

    private static readonly string[] DescBicycleKickElaborate =
    {
        "an outrageous overhead kick",
        "a spectacular bicycle kick into the top corner",
        "a jaw-dropping scissor-kick volley",
        "a sensational acrobatic overhead strike",
        "a breathtaking bicycle kick of pure athleticism",
        "an overhead kick of staggering audacity",
        "a stunning scissor-kick crashed into the net",
        "an overhead kick smashed unstoppably home",
        "a gravity-defying bicycle kick into the corner",
        "an overhead strike of impossible brilliance",
        "a scissor-kick volleyed thunderously into the roof of the net",
        "a bicycle kick that will be replayed forever",
        "an acrobatic overhead effort drilled into the top corner",
        "a spectacular airborne volley beyond the keeper",
        "an overhead kick of breathtaking improvisation",
        "a bicycle kick lashed into the corner from mid-air",
        "a scissor-kick of outrageous technique and timing",
        "an overhead strike that left the stadium gasping",
        "a soaring bicycle kick rifled into the net",
        "an acrobatic scissor-kick of the very highest order",
        "an overhead kick met perfectly and thundered home",
        "a bicycle kick of astonishing power and precision",
        "a spectacular overhead effort into the top corner",
        "a scissor-kick volleyed unstoppably beyond the dive",
        "an overhead kick struck with venom in mid-air",
        "a bicycle kick of sheer balletic genius",
        "an overhead strike that defied belief",
        "a scissor-kick smashed into the upper ninety",
        "a bicycle kick connected flush and rocketed in",
        "an overhead kick of jaw-dropping athleticism into the corner",
        "an acrobatic volley flung into the top corner",
        "a bicycle kick that lit up the tournament",
        "an overhead strike hammered home with breathtaking flair",
        "a scissor-kick of magnificent invention and power",
        "a bicycle kick arrowed into the net from an impossible angle",
        "an overhead kick of pure, unforgettable spectacle",
        "a bicycle kick of staggering athleticism — he was nearly horizontal",
        "an overhead volley rifled in off the inside of the post and crossbar",
        "a scissor-kick of such perfect timing the crowd went silent before erupting",
        "a bicycle kick powered in from twelve yards at a seemingly impossible angle",
        "an overhead effort that climbed, hung, and then crashed into the top corner",
        "a scissor-kick that had the full width of the net to aim at — and found the corner",
        "a bicycle kick of outrageous athleticism and breathtaking accuracy",
        "an overhead kick so perfectly struck the goalkeeper didn't even attempt to move",
        "a scissor-kick of balletic grace and ferocious power in equal measure",
        "a bicycle kick off a driven cross at head height — unstoppable from that distance",
        "an overhead kick struck with the laces and hammered gloriously into the roof of the net",
        "a scissor-kick from a flick-on — first touch overhead, and it's in",
        "an acrobatic overhead finish greeted by the most astonishing roar from the crowd",
        "a bicycle kick that combined every physical attribute a striker could ever possess",
        "an improvised overhead effort defying gravity, physics, and the goalkeeper simultaneously",
    };

    private static readonly string[] DescOwnGoalNeutral =
    {
        "an own goal under pressure",
        "an unfortunate own goal",
        "a deflection into his own net",
        "a misjudged clearance turned in",
        "an own goal off the defender",
        "a cruel own goal",
        "a deflected effort into his own goal",
        "an own goal from a defensive mix-up",
        "a clearance sliced into his own net",
        "an own goal off the boot of the defender",
        "an unlucky deflection past his own keeper",
        "an own goal under the high ball",
        "a touch into his own net at the near post",
        "an own goal from a mistimed clearance",
        "an own goal that wrong-footed the keeper",
        "a deflection that looped into his own net",
        "an own goal from a goalmouth scramble",
        "an own goal turned in at the back post",
        "an own goal off the defender's shin",
        "a clearance that cannoned into his own goal",
        "an own goal from a desperate intervention",
        "an own goal steered past his own keeper",
        "an own goal off a defender's outstretched leg",
        "an unfortunate deflection into the bottom corner of his own net",
        "an own goal under intense pressure in the box",
        "an own goal from a cross that struck the defender",
        "an own goal that crept in off the post",
        "an own goal from a botched clearance",
        "an own goal nudged in while attempting to clear",
        "an own goal off the heel of the defender",
        "an own goal from a deflection nobody could stop",
        "an own goal as the defender stretched to intervene",
        "an own goal turned past his own goalkeeper",
        "an own goal from a wicked deflection",
        "an own goal sliced into his own net under duress",
        "an own goal from a cruel ricochet",
        "an own goal as the defender tried to cut out a dangerous cross",
        "an own goal off the defender's back as he turned to clear",
        "an own goal — a deflection so wicked even the keeper was deceived",
        "an own goal following a goalmouth scramble the defender couldn't escape",
        "an own goal off the defender's hand, raised to protect himself",
        "an own goal from a driven low cross that cannoned in off the standing leg",
        "an own goal as a goalbound shot was deflected past the stranded goalkeeper",
        "an own goal turned in from a corner that swirled wickedly through the box",
        "an own goal after the defender headed away from the line into his own net",
        "an own goal from a shot deflected wildly off a shin and in",
        "an own goal — a clearance off the line that went the wrong side of the post",
        "an own goal following a defensive collapse on the goal-line",
        "an own goal off the chest of a sliding defender attempting to block",
        "an own goal from a free-kick deflected home off the shoulder of the wall",
        "an own goal as the defender completely missed his kick under pressure",
        "an own goal ricocheted in off the heel of a retreating player",
        "an own goal turned in after the keeper parried directly at his own defender",
    };

    // ---------------------------------------------------------------------
    // AssistConnector / SoloEffort / OwnGoal pools.
    // ---------------------------------------------------------------------

    private static readonly string[] AssistConnectors =
    {
        "teed up by",
        "set up by",
        "with the assist from",
        "laid on a plate by",
        "released by",
        "picked out by",
        "fed by",
        "found by",
        "supplied by",
        "served up by",
        "threaded through by",
        "slipped in by",
        "played in by",
        "created by",
        "engineered by",
        "set free by",
        "freed by",
        "carved open by",
        "with the pass from",
        "after a delightful ball from",
        "from the assist of",
        "courtesy of a fine pass from",
        "after being released by",
        "with the through-ball from",
        "off the boot of",
        "after a clever ball from",
        "delivered to him by",
        "presented with the chance by",
        "off the vision of",
        "with the cross from",
        "after a sublime pass from",
        "teed up beautifully by",
        "with the cutback from",
        "from a pinpoint delivery by",
        "with the killer pass from",
        "after the assist by",
        "unlocked by",
        "sprung in behind by",
        "found in the channel by",
        "with a defence-splitting ball from",
        "after a clever flick from",
        "from a cross whipped in by",
        "after a pinpoint delivery from",
        "with the cutback pulled back by",
        "from a through-ball threaded by",
        "after a beautifully timed run opened up by",
        "set in motion by",
        "with the lay-off from",
        "after combining with",
        "via a flowing team move started by",
        "from a square pass slid in by",
        "after a backheel from",
        "with the cushioned header from",
        "after a diagonal switch by",
        "from a perfectly weighted lofted ball by",
        "with the incisive forward pass from",
        "after a run and pull-back from",
        "via a one-two with",
        "set free in behind by",
        "from a corner delivered by",
        "after a quick throw-in cleverly taken by",
        "with the smart reverse pass from",
    };

    private static readonly string[] SoloEfforts =
    {
        "all his own work",
        "a brilliant solo run",
        "he beat his man and finished",
        "a moment of individual magic",
        "a stunning solo effort",
        "entirely his own doing",
        "a piece of individual brilliance",
        "he did it all himself",
        "a mazy run finished off in style",
        "a dazzling solo goal",
        "he danced through and scored",
        "a wonderful individual effort",
        "he glided past them all and finished",
        "a sensational solo strike",
        "he took it from deep and finished alone",
        "a one-man masterclass",
        "he weaved through the defence and scored",
        "an unstoppable solo run",
        "he beat three men and slotted home",
        "a goal carved out single-handedly",
        "he carried it half the length and finished",
        "a breathtaking individual goal",
        "he jinked past the lot of them and scored",
        "no help needed there at all",
        "he ran from inside his own half and finished",
        "a virtuoso solo performance",
        "he shrugged them off and buried it",
        "a goal of pure individual genius",
        "he twisted and turned before finishing",
        "he left defenders trailing and scored",
        "a solo run for the ages",
        "he beat his marker and finished superbly",
        "he conjured it all by himself",
        "a slaloming run finished off alone",
        "he took on the defence and won",
        "a magnificent piece of solo skill",
        "he won it high up the pitch and finished himself",
        "a barnstorming run from box to box, and he finishes it himself",
        "he pressed, won it, and put it away — all his own work",
        "a darting run from deep and he finishes without breaking stride",
        "he skipped past two, muscled past a third, and fired home",
        "he picked it up on the halfway line and never stopped running",
        "a burst of pace, a stepover, and a finish into the corner",
        "he ghosted past the entire defence and finished clinically",
        "a nutmeg, a drag-back, and a devastating finish — pure class",
        "he drove at the defence from forty yards and nobody could stop him",
        "a patient run, waiting for the angle, and an emphatic finish",
        "he accelerated past the last defender and buried it",
        "a searing one-man counter-attack finished with cool precision",
        "he took the ball on his chest, let it drop, and volleyed it home",
        "he spun away from his marker and sprinted clear to score",
        "he showed tremendous strength to hold off the challenge and finish",
        "a solo charge from the centre circle, and an unstoppable finish",
        "he flicked the ball up himself and smashed it on the volley",
        "he dribbled through the entire defence with nothing short of brilliance",
    };

    private static readonly string[] OwnGoals =
    {
        "turns it into his own net",
        "an agonising own goal",
        "he's sliced it past his own keeper",
        "the cruellest of own goals",
        "he's turned it into his own goal",
        "a dreadful own goal",
        "he's deflected it past his own keeper",
        "he's bundled it into his own net",
        "an unfortunate own goal",
        "he's put it through his own goal",
        "he's diverted it into his own net",
        "a calamitous own goal",
        "he's steered it past his own goalkeeper",
        "the most unfortunate of own goals",
        "he's deflected it agonisingly into his own net",
        "he's prodded it into his own goal",
        "a heartbreaking own goal",
        "he's helped it into his own net",
        "he's nudged it past his own keeper",
        "a horrible own goal",
        "he's turned the cross into his own goal",
        "he's sliced it agonisingly into his own net",
        "an own goal he'll want to forget",
        "he's glanced it into his own goal",
        "he's poked it past his own goalkeeper",
        "a gut-wrenching own goal",
        "he's redirected it into his own net",
        "he's looped it over his own keeper",
        "the unkindest own goal you'll see",
        "he's deflected it cruelly into his own goal",
        "he's sent it past his own stranded keeper",
        "a wretched own goal",
        "he's turned it agonisingly into the corner of his own net",
        "he's stabbed it into his own goal under pressure",
        "an own goal of the cruellest kind",
        "he's diverted the ball beyond his own goalkeeper",
        "he's inadvertently steered it into his own net",
        "he's knocked it agonisingly past his own keeper while tracking back",
        "a nightmare own goal — he'll replay that moment all night",
        "he's turned it in with the outside of his boot, into his own goal",
        "the cruellest of deflections sends it past his own stranded keeper",
        "he's glanced a header back, completely misjudging the flight, and it's in",
        "he's thrown himself in front of a shot and redirected it into his own net",
        "he's got a toe to the cross and sent it the wrong way entirely",
        "he's scrambled across only to divert it off his standing foot and in",
        "a dreadful mix-up at the back post and it trickles over his own line",
        "he's headed away from a corner and it's sailed in via the far post",
        "a clearance sliced with the outside of the boot straight into his own net",
        "he's tried to take it away from the striker but sent it beyond his keeper",
        "he's lunged in, made contact, and redirected it to the most unfortunate destination",
        "he's tried to cut it out on the line and kicked it in himself",
        "a deflection off the back of his head as he turned — cruel, but it counts",
    };

    /// <summary>
    /// Returns an exclamatory goal shout whose excitement scales with
    /// <paramref name="vergazo"/>: 8.5+ yields a screamer, 6.5+ an excited
    /// shout, otherwise a routine one. Contains no names, teams or scores.
    /// </summary>
    public static string GoalShout(double vergazo, ref Xoshiro256 rng)
    {
        if (vergazo >= 8.5)
        {
            return GoalShoutsScreamer[rng.NextInt(GoalShoutsScreamer.Length)];
        }

        if (vergazo >= 6.5)
        {
            return GoalShoutsExcited[rng.NextInt(GoalShoutsExcited.Length)];
        }

        return GoalShoutsRoutine[rng.NextInt(GoalShoutsRoutine.Length)];
    }

    /// <summary>
    /// Returns a noun-phrase descriptor of the goal, chosen by
    /// <paramref name="type"/>. For most goal types an elaborate pool is used
    /// when <paramref name="vergazo"/> is at least 7.0, the strike travelled at
    /// least 25 metres, or at least three defenders were beaten; otherwise a
    /// routine pool is used. Own goals use a single neutral pool.
    /// </summary>
    public static string GoalDescriptor(GoalType type, double vergazo, double distanceMeters, int defendersBeaten, ref Xoshiro256 rng)
    {
        bool elaborate = vergazo >= 7.0 || distanceMeters >= 25.0 || defendersBeaten >= 3;

        switch (type)
        {
            case GoalType.OpenPlay:
                return elaborate
                    ? DescOpenPlayElaborate[rng.NextInt(DescOpenPlayElaborate.Length)]
                    : DescOpenPlayRoutine[rng.NextInt(DescOpenPlayRoutine.Length)];

            case GoalType.Header:
                return elaborate
                    ? DescHeaderElaborate[rng.NextInt(DescHeaderElaborate.Length)]
                    : DescHeaderRoutine[rng.NextInt(DescHeaderRoutine.Length)];

            case GoalType.FreeKick:
                return elaborate
                    ? DescFreeKickElaborate[rng.NextInt(DescFreeKickElaborate.Length)]
                    : DescFreeKickRoutine[rng.NextInt(DescFreeKickRoutine.Length)];

            case GoalType.Penalty:
                return elaborate
                    ? DescPenaltyElaborate[rng.NextInt(DescPenaltyElaborate.Length)]
                    : DescPenaltyRoutine[rng.NextInt(DescPenaltyRoutine.Length)];

            case GoalType.LongRange:
                return elaborate
                    ? DescLongRangeElaborate[rng.NextInt(DescLongRangeElaborate.Length)]
                    : DescLongRangeRoutine[rng.NextInt(DescLongRangeRoutine.Length)];

            case GoalType.BicycleKick:
                return elaborate
                    ? DescBicycleKickElaborate[rng.NextInt(DescBicycleKickElaborate.Length)]
                    : DescBicycleKickRoutine[rng.NextInt(DescBicycleKickRoutine.Length)];

            case GoalType.OwnGoal:
            default:
                return DescOwnGoalNeutral[rng.NextInt(DescOwnGoalNeutral.Length)];
        }
    }

    /// <summary>
    /// Returns a connector phrase introducing the provider of an assist
    /// (e.g. "teed up by"). Contains no names, teams or scores.
    /// </summary>
    public static string AssistConnector(ref Xoshiro256 rng)
    {
        return AssistConnectors[rng.NextInt(AssistConnectors.Length)];
    }

    /// <summary>
    /// Returns a phrase describing a goal as an individual solo effort
    /// (e.g. "a brilliant solo run"). Contains no names, teams or scores.
    /// </summary>
    public static string SoloEffort(ref Xoshiro256 rng)
    {
        return SoloEfforts[rng.NextInt(SoloEfforts.Length)];
    }

    /// <summary>
    /// Returns a phrase describing an own goal (e.g. "an agonising own goal").
    /// Contains no names, teams or scores.
    /// </summary>
    public static string OwnGoal(ref Xoshiro256 rng)
    {
        return OwnGoals[rng.NextInt(OwnGoals.Length)];
    }
}
