namespace WorldCup.Engine.Simulation;

using WorldCup.Engine.Random;

/// <summary>
/// Penalty-shootout and serious-injury play-by-play announcer phrase catalogue.
/// Partial of <see cref="CommentaryPhrases"/>. Each pool is a flat array of
/// spoken commentary fragments containing NO player names, team names or scores —
/// the caller layers those in around the chosen fragment.
/// </summary>
public static partial class CommentaryPhrases
{
    private static readonly string[] ShootoutOpeners =
    {
        "Twelve yards, and ice-cold nerves required.",
        "It all comes down to this — the cruellest way to settle it.",
        "Four hundred million people watching, and it boils down to one kick at a time.",
        "Here we go then — the lottery that isn't really a lottery at all.",
        "The longest walk in football starts here.",
        "Heroes will be made, and hearts will be broken, from the spot.",
        "Forty-five minutes, ninety, a hundred and twenty — and now it's down to this.",
        "The keepers step forward, the takers gather, and the agony begins.",
        "Everything they've worked for, distilled into a single swing of the boot.",
        "You can almost hear the heartbeats around this stadium.",
        "No more running, no more tackling — just the ball, the spot, and the nerve.",
        "The bravest game of all is about to be played.",
        "One by one they'll walk up, and one by one the tension will tighten.",
        "This is where legends are forged and reputations destroyed.",
        "The whole world leans in for the most excruciating finale football offers.",
        "A test of nerve like no other in the game.",
        "The tunnel of dread opens, and there's no way around it now.",
        "Composure is the only currency that counts from here.",
        "It's been a war of attrition, and now it's a duel of nerve.",
        "Twelve yards between glory and despair.",
        "The crowd falls into an uneasy hush as the shootout looms.",
        "Strap yourselves in — this is going to be unbearable.",
        "The coin is tossed, the ends are chosen, and the torture begins.",
        "Grown men can barely watch from the halfway line.",
        "The ultimate examination of a footballer's character starts now.",
        "Every kick from here will live with these players forever.",
        "The drama could not be wound any tighter than this.",
        "It's the moment nobody wants but everybody remembers.",
        "Steady hands, steady heads — and a great deal of luck.",
        "The shootout: where careers are defined in a heartbeat.",
        "A hush, then a roar, then a hush again — that's the rhythm to come.",
        "The managers can do nothing now but watch and pray.",
        "This is sport stripped right back to raw, naked nerve.",
        "The penalty spot has never looked so far away.",
        "Here it is — the part of the game that breaks the bravest of hearts.",
        "The arena holds its breath for the spot-kick showdown.",
        "Out they come, the men brave enough to take one.",
        "From here, it's a battle of wills, twelve yards at a time.",
        "The cruellest theatre in all of sport is about to begin.",
        "One kick can make you immortal — or haunt you for a lifetime.",
        "A deathly tension settles as the takers are chosen.",
        "Now we find out who can hold their nerve when it matters most.",
        "The whole tournament, the whole dream, comes down to this.",
    };

    /// <summary>Returns a tension-building opener spoken as a penalty shootout begins.</summary>
    public static string ShootoutOpener(ref Xoshiro256 rng) => ShootoutOpeners[rng.NextInt(ShootoutOpeners.Length)];

    private static readonly string[] ShootoutScoredBank =
    {
        "buries it, top corner!",
        "sends the keeper the wrong way and slots it home",
        "no hesitation — dispatched with absolute conviction",
        "right in the side netting, unstoppable",
        "smashes it down the middle as the keeper dives away",
        "tucks it calmly into the bottom corner",
        "rolls it home with ice in his veins",
        "drills it low and hard beyond the dive",
        "places it perfectly into the corner — flawless",
        "lashes it into the roof of the net",
        "keeps his nerve and finds the corner",
        "side-foots it past the keeper with total composure",
        "thumps it high into the net — emphatic",
        "fizzes it into the bottom corner, no chance for the keeper",
        "strokes it home as cool as you like",
        "powers it past the keeper's outstretched glove",
        "guides it into the corner with surgical precision",
        "rifles it into the top corner — magnificent under pressure",
        "sends the keeper one way and the ball the other",
        "crashes it into the net and lets out a roar",
        "dinks it down the middle — what audacity!",
        "finishes with the calm of a man on the training ground",
        "blasts it into the corner and the net bulges",
        "makes no mistake from twelve yards",
        "dispatches it with the swagger of a born finisher",
        "buries it low to the keeper's right",
        "slams it into the top bins, unreachable",
        "converts with absolute authority",
        "plants it firmly into the corner",
        "keeps it down and steers it past the dive",
        "hammers it home and points to the sky",
        "sweeps it into the net without a flicker of doubt",
        "strikes it true and the keeper never had a sniff",
        "tucks it away with nerveless precision",
        "drives it into the corner and turns away in triumph",
        "lifts it into the net as the keeper goes early",
        "finds the corner with a beautifully struck spot-kick",
        "thrashes it past the keeper — clinical from twelve yards",
        "rolls it into the empty corner, keeper sent the wrong way",
        "curls it just inside the post — unsavable",
        "smashes it home and beats his chest to the crowd",
        "places it inch-perfect beyond the despairing dive",
        "dispatches it coolly despite the weight of the world on his shoulders",
    };

    /// <summary>Returns a phrase describing a converted shootout penalty.</summary>
    public static string ShootoutScored(ref Xoshiro256 rng) => ShootoutScoredBank[rng.NextInt(ShootoutScoredBank.Length)];

    private static readonly string[] ShootoutMissedBank =
    {
        "skies it over the bar!",
        "off the post and away — agony!",
        "drags it horribly wide",
        "puts it into Row Z — what a moment to miss",
        "blazes it high over the crossbar",
        "smashes it against the bar and away to safety",
        "clatters the upright — and it stays out!",
        "scoops it well over — a dreadful miss",
        "pulls it wide of the far post",
        "rattles the woodwork and the chance is gone",
        "balloons it into the stands — heartbreak",
        "fires it wide of the upright — unbelievable",
        "slips as he strikes and screws it wide",
        "thumps it off the crossbar and over",
        "sends it sailing high and wide",
        "shanks it horribly off target",
        "hooks it past the post — a glorious chance squandered",
        "leans back and lashes it over the top",
        "wraps his foot around it and drags it wide of the post",
        "fluffs his lines and puts it well over the bar",
        "cannons it off the post and watches it bounce clear",
        "gets under it and balloons it into the crowd",
        "drives it miles over — he cannot believe it",
        "places it too close and clips the post — out it stays",
        "completely mishits it and it trundles wide",
        "smacks the bar and the ball bounces to safety",
        "sends it over and sinks to his knees",
        "misses the target altogether — sliced horribly wide",
        "strikes the upright and the rebound flies clear",
        "puts his spot-kick into the night sky",
        "hammers it onto the bar and the keeper breathes again",
        "drags his effort wide and holds his head in his hands",
        "blasts it over when he simply had to score",
        "clips the outside of the post — so close, yet no goal",
        "lifts it over from twelve yards — a moment to forget",
        "screws it wide of the left-hand upright",
        "hits it off the woodwork twice and out — cruel luck",
        "sends it spinning wide off the post",
        "scuffs it and the ball rolls apologetically wide",
        "thrashes it over the bar and the crowd groans as one",
        "smashes it against the angle of post and bar — out!",
        "sends it wide and the agony is written all over his face",
        "drags it across the face of goal and wide of everything",
    };

    /// <summary>Returns a phrase describing a shootout penalty missed off target or off the woodwork.</summary>
    public static string ShootoutMissed(ref Xoshiro256 rng) => ShootoutMissedBank[rng.NextInt(ShootoutMissedBank.Length)];

    private static readonly string[] ShootoutSavedBank =
    {
        "SAVED! The keeper guesses right and flings out a strong hand!",
        "down low to his left — and he's kept it out!",
        "a colossal save — the gloves are the hero!",
        "SAVED! He reads it perfectly and gets down brilliantly!",
        "the keeper hurls himself to his right and claws it clear!",
        "what a stop — he's denied him from twelve yards!",
        "SAVED! Strong wrists turn it away to safety!",
        "the keeper stands tall and smothers it — magnificent!",
        "down he goes and the penalty is beaten away!",
        "SAVED! A heroic dive to keep it out!",
        "the keeper springs across and tips it onto the post!",
        "he picks the corner and gets a firm hand to it — saved!",
        "SAVED! The keeper has won this for his side!",
        "a fingertip is just enough to divert it wide!",
        "the keeper plunges full stretch and repels it!",
        "SAVED! He stayed big and the taker blinked first!",
        "the keeper guesses correctly and parries it clear!",
        "what a save — he read the run-up like a book!",
        "SAVED! Down to his right and a strong palm keeps it out!",
        "the keeper waits, waits, and then dives to deny him!",
        "a stunning reaction stop from the spot — saved!",
        "the keeper throws up an arm and blocks it brilliantly!",
        "SAVED! He gets down low and holds it firm!",
        "the keeper anticipates it and pushes it round the post!",
        "a save of immense bravery and timing — kept out!",
        "the keeper flies across his line and gets there — saved!",
        "SAVED! The keeper becomes the hero of the hour!",
        "he picked his side perfectly and made the stop!",
        "the keeper smothers it with his legs — what a save!",
        "SAVED! An outstanding low dive turns it aside!",
        "the keeper claws it away and the bench leaps as one!",
        "he gets a strong hand behind it and holds on — saved!",
        "SAVED! He denied him with nerve and a magnificent dive!",
        "the keeper guesses right and the spot-kick is foiled!",
        "down to his left and the penalty is repelled — heroics!",
        "the keeper produces a save out of the very top drawer!",
        "SAVED! He sprawled to his right and clawed it away!",
        "the keeper stands firm and parries it to safety!",
        "what a moment — the keeper has kept his side alive!",
        "SAVED! A brilliant, brave, decisive stop from the spot!",
        "the keeper reads it, dives, and gets a glove to it!",
        "he refused to move early and was rewarded — saved!",
        "the keeper denies him at the death and roars to the heavens!",
    };

    /// <summary>Returns a phrase describing a shootout penalty saved by the goalkeeper.</summary>
    public static string ShootoutSaved(ref Xoshiro256 rng) => ShootoutSavedBank[rng.NextInt(ShootoutSavedBank.Length)];

    private static readonly string[] ShootoutPressureBank =
    {
        "This, to win the World Cup tie…",
        "Miss this and they're going home…",
        "The whole tournament on his shoulders now…",
        "Score, and they are through to the next round…",
        "Everything rides on this one swing of the boot…",
        "Get this wrong and it's all over for his side…",
        "This kick to keep the dream alive…",
        "Bury it, and the bench will spill onto the pitch…",
        "He must score, or it ends right here…",
        "The weight of a nation on this single penalty…",
        "This, to send them through and break a million hearts…",
        "No second chances now — it's score or go home…",
        "One kick from glory, one kick from despair…",
        "He has to find the net, or the journey ends…",
        "This penalty could win the whole thing…",
        "Convert, and they survive to fight another kick…",
        "Everything they've fought for comes down to this strike…",
        "Miss, and the agony of an early exit awaits…",
        "This, to make himself a hero forever…",
        "He knows what's riding on it — the whole world does…",
        "Score this and they march on; miss and they're done…",
        "The loneliest twelve yards in all of football, this…",
        "His entire tournament in the balance with this kick…",
        "This penalty to keep them breathing in the competition…",
        "Net it, and the celebrations will be wild…",
        "If he misses, it's heartbreak and the long road home…",
        "This is the kick that could decide everything…",
        "The pressure could not possibly be greater than this…",
        "He must hold his nerve, or it's curtains…",
        "This, to settle it once and for all…",
        "One mistake here and the dream dies…",
        "The whole stadium dares not breathe for this one…",
        "This kick carries the hopes of millions…",
        "Score and stay alive; miss and it's over…",
        "His country holds its breath for this single moment…",
        "This penalty to write his name into the history books…",
        "Bury this and they take an enormous step towards the next round…",
        "He simply cannot afford to miss this one…",
        "Everything has led to this — the loneliest of moments…",
        "This kick to break the deadlock and break some hearts…",
        "All eyes, all hopes, all fears — on this single penalty…",
        "He carries the burden of an entire campaign right now…",
        "Miss this, and a summer of dreams comes crashing down…",
    };

    /// <summary>Returns a high-pressure line spoken just before a decisive or must-score shootout kick.</summary>
    public static string ShootoutPressure(ref Xoshiro256 rng) => ShootoutPressureBank[rng.NextInt(ShootoutPressureBank.Length)];

    private static readonly string[] ShootoutSuddenDeathBank =
    {
        "Sudden death now — one blink and it's over.",
        "No margin for error any longer.",
        "Every kick a potential ending.",
        "We're into sudden death, where one miss is fatal.",
        "From here, a single slip decides the whole thing.",
        "Score and survive, miss and it's done — that's sudden death.",
        "The safety net is gone now; this is the high wire.",
        "One mistake from either side and the curtain falls.",
        "Sudden death — the cruellest twist in the cruellest contest.",
        "Now it's nerve against nerve, kick for kick, to the bitter end.",
        "Every penalty from here could be the last.",
        "We're beyond the regulation kicks — it's do or die.",
        "Each taker walks up knowing a miss ends it all.",
        "The tension is almost unbearable as sudden death begins.",
        "One slip, and a whole campaign evaporates.",
        "No room to breathe now — every kick is decisive.",
        "We've reached the part where heartbreak is one swing away.",
        "It's blow for blow now, and the next mistake is terminal.",
        "Sudden death — and you can scarcely watch.",
        "The margins have vanished; this is win or perish.",
        "From this kick on, there's no coming back from a miss.",
        "We're trading punches now, and one will land fatally.",
        "The pressure cranks to breaking point in sudden death.",
        "Score to stay alive — there is no other option now.",
        "Every walk to the spot could be the final one.",
        "It's nerve-shredding now: miss and the journey ends instantly.",
        "Sudden death, where the brave inherit everything.",
        "The slightest error and it's all over in a heartbeat.",
        "We go again, but now a single miss is decisive.",
        "This is football's most agonising form of Russian roulette.",
        "Kick for kick, heartbeat for heartbeat, until someone cracks.",
        "There's nowhere to hide in sudden death.",
        "One flinch, one flicker of doubt, and it ends.",
        "The takers know it — there is no tomorrow if they miss.",
        "Sudden death, and the whole world dare not look away.",
        "Now the smallest mistake carries the heaviest price.",
        "We're down to the wire — each kick could close the book.",
        "It's a duel to the last nerve now.",
        "Miss here and there is no reprieve whatsoever.",
        "The contest hangs by a thread with every single kick.",
        "Sudden death — where champions are separated from the rest.",
        "From now on, every penalty is a matter of life and death for the tie.",
        "One after another they go, and one of them will end it.",
    };

    /// <summary>Returns a line spoken on entering or continuing sudden-death penalties.</summary>
    public static string ShootoutSuddenDeath(ref Xoshiro256 rng) => ShootoutSuddenDeathBank[rng.NextInt(ShootoutSuddenDeathBank.Length)];

    private static readonly string[] ShootoutWonBank =
    {
        "And that's it — they've done it from the spot!",
        "Pandemonium! They win the shootout and the bench empties!",
        "Heartbreak for one, ecstasy for the other.",
        "It's over — and the celebrations are utterly wild!",
        "They've won it! The keeper is mobbed by his teammates!",
        "And the shootout is settled — sheer, unbridled joy!",
        "That's the one! They march on and the dream lives!",
        "It's done — and there are grown men in tears all over the pitch!",
        "The agony and the ecstasy, side by side, in a single instant!",
        "They've held their nerve and they're through!",
        "And the whole squad sprints to celebrate as one!",
        "It's won and lost in the cruellest, most beautiful way!",
        "The decisive kick — and they have prevailed!",
        "Joy unconfined for one side, utter devastation for the other!",
        "And that settles it — they've come through the ordeal!",
        "The shootout is theirs — what scenes, what drama!",
        "They've done it the hard way, and the celebrations erupt!",
        "It's all over — and a wave of emotion sweeps the stadium!",
        "The winning kick is struck, and bedlam breaks loose!",
        "And the keeper falls to the turf as his teammates pile on!",
        "They survive the shootout — and the relief is overwhelming!",
        "That's the moment — they're through, and the party begins!",
        "Triumph and despair, separated by a single penalty!",
        "And they've won it from twelve yards — pure euphoria!",
        "The bench clears, the staff sprint on — they've made it!",
        "It's decided, and one side collapses in heartbreak while the other soars!",
        "They've come through the cauldron — and they are jubilant!",
        "And the final kick settles a contest for the ages!",
        "They win the shootout, and a nation can breathe again!",
        "Ecstasy at one end, inconsolable grief at the other!",
        "And that is that — they have won the shootout!",
        "The dream is alive — they've conquered the spot-kicks!",
        "It's theirs! The players race to the corner in delirium!",
        "And the heartache is total for the vanquished, the joy boundless for the victors!",
        "They've prevailed in the most nerve-shredding way imaginable!",
        "And so the shootout delivers its verdict — they go through!",
        "What a moment — they've won it, and the noise is deafening!",
        "It's over, and the emotions pour out in every direction!",
        "They've done it! Twelve yards from despair, and they've triumphed!",
        "And the shootout drama ends in scenes of wild celebration!",
        "The winning penalty — and the entire bench takes flight!",
        "They've held firm to the last, and the spoils are theirs!",
        "And it's settled — the cruellest contest hands them the sweetest of victories!",
    };

    /// <summary>Returns a line marking the moment a penalty shootout is decided.</summary>
    public static string ShootoutWon(ref Xoshiro256 rng) => ShootoutWonBank[rng.NextInt(ShootoutWonBank.Length)];

    private static readonly string[] SeriousInjuryReactions =
    {
        "Oh, that looks bad — you fear the worst with that one.",
        "He knew straight away; you could see it in his face. That could be months, not weeks.",
        "A horrible sight, and a real blow — his tournament may be over right there.",
        "That's a sickening one, and you don't want to see the replay.",
        "He's in real trouble here — that has the look of something serious.",
        "The way he went down tells you everything; that's not a knock, that's an injury.",
        "You hate to see it — the physios' faces say it all.",
        "That's the kind of moment that ends a player's summer in an instant.",
        "He's signalling to the bench already; he knows this is a bad one.",
        "I'm afraid that has the hallmarks of a serious one.",
        "The stretcher is coming, and that tells its own grim story.",
        "He's holding it and shaking his head — that is heartbreaking to watch.",
        "That looked like it went the wrong way; you fear ligaments there.",
        "A dreadful blow, and his face is a picture of pure anguish.",
        "He won't be continuing — and you suspect not for some time.",
        "That's a cruel, cruel moment for a player at the peak of a tournament.",
        "The silence around the ground tells you how serious this is.",
        "He's distraught, and so are his teammates gathered around him.",
        "That has the look of a fracture — you could almost hear it.",
        "His World Cup may have just ended in the most brutal fashion.",
        "You can see the medical staff are deeply concerned.",
        "That's an awful one, and there's no way he carries on after that.",
        "He's covering his face — he fears the worst, and so do we.",
        "A genuinely worrying sight, and the whole bench is on its feet.",
        "That kind of injury can take a player out for the best part of a year.",
        "He's being given oxygen — that's how serious this has become.",
        "The grimace tells you all you need to know; that's a bad one.",
        "Teammates are calling for help urgently — never a good sign.",
        "That's the injury every player dreads, and it's struck at the worst time.",
        "He's pounding the turf in frustration and pain — it's heartbreaking.",
        "I fear that's a long lay-off, possibly even longer.",
        "The physio isn't rushing the assessment — and that worries me greatly.",
        "He went into the challenge fine and came out of it in agony.",
        "That's a season-defining injury, and it's come from nowhere.",
        "You sense his tournament, perhaps more, has just been taken from him.",
        "The look on the manager's face says this one is serious.",
        "He can't put any weight on it at all — that's deeply concerning.",
        "A horrible, freak moment, and a player's dreams in tatters.",
        "That's not one he'll shake off; the stretcher confirms our fears.",
        "He's being carried off, and the applause is laced with real sympathy.",
        "I've seen that injury before, and it's rarely anything but serious.",
        "The whole stadium has gone quiet, and that says everything.",
        "A devastating blow — you wouldn't wish that on any player.",
    };

    /// <summary>Returns a colour-analyst reaction to an apparently serious injury such as a fracture or ligament damage.</summary>
    public static string SeriousInjuryReaction(ref Xoshiro256 rng) => SeriousInjuryReactions[rng.NextInt(SeriousInjuryReactions.Length)];
}
