namespace WorldCup.Engine.Simulation;

using WorldCup.Engine.Random;

/// <summary>
/// Play-by-play announcer phrase catalogue covering match-flow moments:
/// scene-setting, period transitions, controversy, defensive errors,
/// ambient filler and colour-analyst asides.
/// </summary>
public static partial class CommentaryPhrases
{
    private static readonly string[] IntroOpeners =
    {
        "Good evening and welcome to a packed stadium",
        "Good evening and welcome, football fans the world over",
        "A warm welcome to you all on what promises to be a special night",
        "Welcome along to a stadium positively crackling with anticipation",
        "Good evening and a very warm welcome wherever you're watching from",
        "What an atmosphere already as we welcome you to tonight's showdown",
        "Hello and welcome to a cauldron of noise and colour",
        "A glorious evening here and the stage could not be better set",
        "Welcome one and all to a contest the whole world has been waiting for",
        "Good evening — the flags are flying and the anthems have barely faded",
        "Welcome to a night that could live long in the memory",
        "The tension is palpable as we welcome you to this one",
        "Good evening, and what a privilege it is to bring you tonight's drama",
        "Welcome along — the stands are a sea of colour from end to end",
        "A spine-tingling welcome to you all under the lights tonight",
        "Greetings from a stadium that is absolutely heaving",
        "Welcome to the showpiece — and you can feel the electricity",
        "Good evening from a ground bursting at the seams",
        "Hello and welcome to ninety minutes — perhaps more — of pure theatre",
        "Welcome along on a night thick with expectation",
        "A very good evening to you as the great occasion finally arrives",
        "Welcome to the big one — and there's a real edge in the air",
        "Good evening from pitchside, where the noise is already deafening",
        "Welcome, everybody, to a fixture dripping with history",
        "The scene is set, the crowd is roaring — welcome along",
        "Good evening and welcome to what should be a feast of football",
        "Hello and welcome — you join us on a truly unforgettable night",
        "Welcome to the heart of the action on a balmy evening",
        "Good evening — settle in, because this one has everything to live up to",
        "A wonderful welcome to you all from a sold-out arena",
        "Welcome along — the whole nation, both nations, hold their breath",
        "Good evening from a stadium shaking with anticipation",
        "Welcome to a night when reputations will be made",
        "Hello and welcome — the bunting is up and the dream is alive",
        "Good evening, and what a treat we have in store for you",
        "Welcome to the grand stage, where legends are forged",
        "Good afternoon and welcome to this magnificent arena",
        "Hello from a ground that hasn't stopped buzzing since the gates opened",
        "Welcome to what the football world has been talking about all week",
        "Good evening and welcome to a venue steeped in footballing history",
        "Greetings to you all as we count down to the opening whistle",
        "A rapturous welcome to you from a stadium already on its feet",
        "Welcome along on an evening that promises drama from first to last",
        "Hello and welcome — both sets of fans in tremendous voice already",
        "Good evening from an arena where history is about to be made",
        "Welcome to the biggest stage of all — the tension is almost unbearable",
        "A very warm hello to you all as the great occasion draws near",
        "Welcome — the pitch is gleaming, the crowd is roaring, and we are ready",
        "Good evening and welcome to a contest that needs no introduction",
        "Hello and welcome from a stadium that is fit to burst",
        "Welcome along to a night already alive with noise and colour",
        "Good evening — and wherever you're joining us from, thank you for being here",
        "Welcome to a fixture that carries the weight of nations on its shoulders",
        "Hello from the best seat in the house on a magnificent night for football",
        "Welcome — every seat taken, every eye fixed on that pitch below",
        "Good evening and a tremendous welcome to tonight's blockbuster",
        "Welcome along to a stadium bathed in floodlights and full of expectancy",
        "Good evening — the players are in the tunnel and the moment is almost upon us",
        "Hello and welcome to what could be one of the great nights of this tournament",
        "Welcome to the arena — and you can hear the roar even out here on the pitch",
        "Good evening from a stadium where the noise has not dropped since kick-off build-up began",
        "Welcome along — the banners are raised, the colours are flying, and we are set",
        "A very good evening to every single one of you tuning in for this one",
        "Welcome to the pinnacle — it doesn't get much bigger than this in world football",
        "Good evening and welcome to a night we have all been eagerly awaiting",
        "Hello from a ground where the anticipation has been building all day long",
        "Welcome along on a night drenched in significance and football romance",
        "Good evening — the anthems have stirred the soul and now for the match itself",
    };

    private static readonly string[] KickoffLines =
    {
        "And the referee blows for the start — we're underway!",
        "We're off! The whistle goes and battle commences.",
        "And away we go — the match is alive!",
        "The referee gets us started and we are underway.",
        "Here we go then — the opening whistle has sounded!",
        "And it begins! The ball is rolling at last.",
        "We're up and running — game on!",
        "The whistle peeps and the contest is finally upon us.",
        "And they're off — the long wait is over!",
        "Underway at last — and the crowd lets out a roar.",
        "The referee signals and we have a football match!",
        "And the first touch is taken — we are live!",
        "Off they go — the journey begins right here.",
        "The shrill of the whistle, and we are away!",
        "And so it starts — let the drama unfold.",
        "We have lift-off — the match is in motion!",
        "The opening exchanges begin — we're underway!",
        "And the ball is in play — here we go!",
        "Kicked off and we're racing already.",
        "The referee's whistle cuts the air — game on!",
        "And we are off and running under the lights.",
        "There's the whistle — the action is finally here!",
        "Away we go, and you sense both sides mean business.",
        "The match springs into life — we are underway!",
        "And it's all systems go from the first whistle.",
        "The ball is struck and the contest has begun.",
        "Here we are then — the referee gets it all moving.",
        "And we're into it — no easing-in period here!",
        "The whistle blows, the crowd erupts, and we're away.",
        "And the great occasion is finally a football match!",
        "Off and rolling — the opening salvos are fired.",
        "The referee starts the clock and away we go.",
        "And there it is — the first whistle of the night!",
        "We are underway, and you can cut the tension with a knife.",
        "The ball is moving and so is this great occasion.",
        "And the dream becomes reality — we're underway!",
        "The referee gets the proceedings started — off we go!",
        "A tap and we're into this magnificent contest.",
        "And the stadium erupts as the first whistle sounds — underway!",
        "Here we go — the moment of truth has finally arrived.",
        "The opening pass is played and we are live!",
        "That's the signal — and the match is officially on.",
        "We've been waiting all day for this — and now here it is!",
        "A clean blow of the whistle and we're into it.",
        "And the match bursts into life — absolutely underway!",
        "The referee sets the clock ticking — let's go!",
        "And with a blast of that whistle, history beckons.",
        "Off they go — and the crowd hasn't stopped since.",
        "The first whistle shatters the silence — we're live!",
        "And we are going! The match is under way at last.",
        "The ball rolls forward and the contest ignites.",
        "There's no holding back now — the referee has sent us on our way.",
        "And right from that first whistle, both teams are at it.",
        "A roar from the stands as the referee gets us going.",
        "And the long build-up ends here — we're underway!",
        "The coin has been tossed, the whistle has blown — let's play!",
        "Off and running, and the intensity is already remarkable.",
        "The starting gun fires and we are away into this one.",
    };

    private static readonly string[] SecondHalfLines =
    {
        "We're back under way for the second half.",
        "And we're off again for the second forty-five.",
        "The second half is up and running.",
        "Back from the break, and the action resumes.",
        "The referee restarts and we're into the second half.",
        "And away we go once more — second half under way.",
        "Out they come, and the second period begins.",
        "Refreshed and reset, both sides resume the battle.",
        "The whistle goes and the second half is alive.",
        "And here we go again — forty-five more to play.",
        "Back to business as the second half kicks off.",
        "The second period is under way and the tempo lifts.",
        "We resume, and you sense a renewed urgency.",
        "And it's game on again after the interval.",
        "The teams re-emerge and the second half springs to life.",
        "Underway again — the closing act begins.",
        "And the second half gets going without delay.",
        "Back under the lights for the second forty-five.",
        "The referee signals and we're rolling once more.",
        "And we restart, the stakes higher than ever.",
        "The second half begins, and there's everything still to play for.",
        "Out of the blocks again as the second period starts.",
        "And we're away for the second half — buckle up.",
        "The interval is over and the contest reignites.",
        "Second half under way, and the crowd finds its voice again.",
        "And here we go for the run to the finish.",
        "The whistle peeps and the second half is on.",
        "Resumed, restarted, and right back into the fray.",
        "And the second half is upon us — no time to settle.",
        "Back into it, with the destiny of the match still open.",
        "The second period kicks off and the drama continues.",
        "And we're under way again — the decisive half awaits.",
        "Out they stride, and the second half roars into life.",
        "The action resumes — second half, here we come.",
        "And the closing forty-five is under way at last.",
        "Restarted, and the tension ratchets up another notch.",
        "The teams are back, the referee is happy — off we go again.",
        "And it's all to play for as the second half begins.",
        "The dressing-room talks are done — time to deliver.",
        "Out come the players once more, and you sense a shift in intent.",
        "Second half under way, and the opening exchanges are purposeful.",
        "The interval has done nothing to dull the intensity — we're straight into it.",
        "And the second act gets going — this match has much more to give.",
        "We're back and the clock is ticking down on forty-five vital minutes.",
        "The team talks are over and it's time to put words into action.",
        "Second half, and both teams look refreshed and determined.",
        "And away we go once more — the second half roars into life.",
        "The crowd lifts and the second half begins with real purpose.",
        "We're underway for the second forty-five — and not a moment to spare.",
        "The referee gets us going again and the tempo is instant.",
        "And there's the restart — the second half is on!",
        "Back into the cauldron — the second half is underway.",
        "The players hardly needed the break — they're straight at it.",
        "And the second half begins exactly where the first left off.",
        "Restarted — and both sides look eager to seize the initiative.",
        "Out they come for the second half, and the noise is extraordinary.",
        "The closing chapter begins — second half underway!",
        "And here we are again, forty-five more minutes of football awaiting us.",
    };

    private static readonly string[] HalfTimeLines =
    {
        "And that's the half-time whistle.",
        "The referee calls a halt — it's half time.",
        "And there's the whistle to end the first half.",
        "Time for a breather — that's half time.",
        "The first forty-five is up, and we pause.",
        "And the whistle sounds for the interval.",
        "Half time arrives, and there's plenty to chew over.",
        "The referee brings the half to a close.",
        "And that's it for the first period — half time.",
        "Whistle goes, and the players head for the tunnel.",
        "The first half is done and dusted.",
        "And we reach the interval at last.",
        "That'll be half time, and a chance to draw breath.",
        "The opening forty-five comes to an end.",
        "And there it is — the half-time break is upon us.",
        "The referee signals, and it's time for the team talks.",
        "Half time, and the tactics board will be busy.",
        "And the first half is brought to a close.",
        "The whistle peeps and we pause for the interval.",
        "That's the first half wrapped up.",
        "And off they go for a well-earned rest — half time.",
        "The referee ends the half, and there's lots to discuss.",
        "And we've reached the midway point of the match.",
        "Half-time whistle, and a moment to reflect.",
        "The first period closes, and the break begins.",
        "And that's the lot for the opening forty-five.",
        "Time called on the first half by the referee.",
        "And it's into the tunnel as half time arrives.",
        "The whistle goes — fifteen minutes to regroup.",
        "Half time, and both managers have thinking to do.",
        "And there's the break — the first act is complete.",
        "The referee whistles for the interval, right on schedule.",
        "And we pause the proceedings — that's half time.",
        "The first half signs off, and the break is here.",
        "And that's the half-time whistle, with much still to play for.",
        "Time for oranges and instructions — it's half time.",
        "The whistle signals the interval and the players are off.",
        "And that is the half, and what a forty-five it has been.",
        "Half time — the first chapter is written, the second awaits.",
        "The referee ends the half and gives both sides time to breathe.",
        "And the break arrives — there is so much to ponder in those dressing rooms.",
        "Half time, and the crowd buzzes with debate.",
        "The first forty-five are in the books — what a story so far.",
        "And there's the whistle — both managers will have plenty to say.",
        "Half-time break, and the players troop off to collect their thoughts.",
        "That brings the curtain down on the opening period — half time.",
        "The referee's whistle sounds and a fascinating first half ends.",
        "And we pause — the scores, the talking points, the tactical questions all pile up.",
        "Half time, and the momentum could swing either way in the second period.",
        "The first half closes with the contest beautifully poised.",
        "And off they go — fifteen precious minutes to reshape the game.",
        "That's half time — and the second half could go absolutely anywhere.",
        "The referee calls a halt to a lively first half — interval time.",
        "And there's the interval whistle — much to reflect upon.",
        "Half time on a match that has given us everything and then some.",
        "The whistle brings the half to an end and we have a real game on our hands.",
        "Half time — and the managers earn their wages in the next fifteen minutes.",
    };

    private static readonly string[] FullTimeLines =
    {
        "It's all over! The final whistle has gone.",
        "And that's it — the referee blows for full time!",
        "The final whistle sounds — the match is done!",
        "It's finished! Full time at last.",
        "And there's the whistle — it's all over!",
        "The referee calls time, and the contest is complete.",
        "Full time! The drama has reached its conclusion.",
        "And that's the end — the final whistle has blown!",
        "It's over! Ninety-odd minutes come to a close.",
        "The whistle goes for the last time tonight.",
        "And there it is — full time, the match is settled.",
        "The referee ends it — and what a match it has been!",
        "Full time, and the final reckoning is in.",
        "And the curtain comes down — it's all over!",
        "The final whistle pierces the air — we're done!",
        "And that brings the contest to its end.",
        "It's finished! The referee blows the final whistle.",
        "Full time, and the players sink to the turf.",
        "And we've reached the end of the road — it's over!",
        "The whistle sounds, and the battle is concluded.",
        "And that's full time — the result is sealed.",
        "It's all over here, and what a journey it's been!",
        "The referee brings proceedings to a close at last.",
        "Full time! The dust settles on a memorable night.",
        "And there's the final whistle — the story is told.",
        "It's done and dusted — full time has arrived.",
        "The match reaches its conclusion with that whistle.",
        "And that's the end of it — the referee says no more!",
        "Full time, and the emotions pour out across the pitch.",
        "The final whistle goes — the verdict is delivered.",
        "And we've crossed the finish line — it's all over!",
        "The referee blows up, and the contest is history.",
        "Full time! Ninety minutes and more come to an end.",
        "And that is that — the final whistle has sounded.",
        "It's over at the last — the referee ends the game.",
        "And the match draws to its close — full time!",
        "Three blasts of the whistle and it's done — full time!",
        "And the referee puts this one to bed — that's full time.",
        "The whistle blows and this extraordinary contest is over.",
        "Full time, and the crowd erupts with every emotion imaginable.",
        "And that's your lot — the referee draws the curtain on a wonderful match.",
        "It's all over — and the players know exactly what it means.",
        "The final act is complete — full time, and what a night this has been.",
        "And with that whistle, the scoreline is set in stone.",
        "Full time, and tears and elation in equal measure out there.",
        "The referee raises the whistle one last time — and that's it, full time!",
        "And the match has had its say — full time at last.",
        "It's over! The final whistle delivers its verdict.",
        "And so ends a contest that gripped us from first minute to last.",
        "Full time — and the history books are already being updated.",
        "The final whistle ends a match no one in this ground will forget.",
        "And that concludes proceedings — full time, and what a game that was.",
        "The referee calls it — and the dreams of one side are extinguished.",
        "Full time, and the celebrations — or the heartbreak — begin immediately.",
        "And that's the full-time whistle, closing a chapter in this tournament's story.",
        "It's finished — and the scoreline will be debated for a long time to come.",
        "The last whistle sounds and everything that follows belongs to the history books.",
        "Full time! The roar tells you all you need to know about what this means.",
    };

    private static readonly string[] ExtraTimeLines =
    {
        "We go to extra time.",
        "And it'll be settled in extra time.",
        "There's no separating them — extra time it is.",
        "We need an extra thirty minutes to find a winner.",
        "And so we head into extra time.",
        "Deadlocked at the end — on to extra time.",
        "It's level, and the additional period beckons.",
        "We can't be separated — extra time awaits.",
        "And the players brace themselves for extra time.",
        "No winner yet — we go to the extra half-hour.",
        "And it spills over into extra time.",
        "Locked together, so extra time will decide it.",
        "We push on into an additional thirty minutes.",
        "And there's more to come — it's extra time.",
        "Neither side could find a way through — extra time.",
        "And the contest extends into extra time.",
        "Tied at the finish, and now the extra period.",
        "We go again — extra time is upon us.",
        "And the drama stretches into extra time.",
        "Still all square, so we head for extra time.",
        "The match needs more — extra time it is.",
        "And weary legs must summon yet more — extra time.",
        "Nothing to choose between them, so extra time.",
        "And we're into the additional thirty minutes.",
        "It goes the distance — extra time now.",
        "And the marathon continues into extra time.",
        "We could not find a winner, so extra time arrives.",
        "And on we go — the extra period awaits.",
        "Level after ninety, and extra time will tell.",
        "We move to extra time to settle this.",
        "And the players gather themselves for extra time.",
        "It's all square, and extra time is the next chapter.",
        "And we head into the extra session.",
        "No breakthrough yet — extra time will decide.",
        "And the night gets longer — we go to extra time.",
        "Still deadlocked, and so extra time it must be.",
        "The thirty additional minutes will have to do the job.",
        "And the players dig deep as extra time looms.",
        "Ninety minutes couldn't split them — we push on into extra time.",
        "And the stadium holds its collective breath as extra time begins.",
        "Neither side blinked — and so extra time awaits both of them.",
        "Remarkable — ninety minutes and still no winner. Extra time it is.",
        "And exhausted bodies must find fresh reserves for extra time.",
        "We're going the full route — extra time is here.",
        "And the managers must find the right words as extra time approaches.",
        "The match refuses to be decided — into extra time we go.",
        "And with extra time upon us, anything and everything is still possible.",
        "Two sides equal on the night — the extra period will separate them.",
        "And so we play on — thirty more minutes of football to find a winner.",
        "The tension is at breaking point as extra time gets under way.",
        "Neither goalkeeper could be beaten in ninety — let's see what extra time brings.",
        "We go again, and the drama intensifies with every passing minute.",
        "And the supporters can barely watch as extra time kicks off.",
        "An extra thirty minutes — and at this stage, every moment will feel enormous.",
        "And the contest refuses to die — extra time delivers a fresh chapter.",
        "We're into the added period, and nerves are shredded right across the stadium.",
    };

    private static readonly string[] ShootoutLines =
    {
        "It will be settled from the penalty spot.",
        "And it comes down to penalties.",
        "There's nothing between them — a shootout will decide.",
        "We go to the lottery of spot kicks.",
        "And the drama heads to the penalty spot.",
        "It'll be decided from twelve yards.",
        "A shootout it is — nerves of steel required now.",
        "And the cruellest of finishes awaits — penalties.",
        "We can't separate them, so it's penalty kicks.",
        "And the tension cranks up — a shootout to come.",
        "It goes to penalties, and hearts are in mouths.",
        "The match will be settled in a shootout.",
        "And from the spot, the winner will be found.",
        "Penalties it is — the ultimate test of nerve.",
        "And we head for the most agonising of endings.",
        "It comes down to this — a penalty shootout.",
        "And destiny will be decided from twelve yards.",
        "A shootout beckons, and you can feel the dread.",
        "There's no other way — penalties will settle it.",
        "And the spot kicks will determine who goes through.",
        "We go to a shootout — pure theatre and torture.",
        "And the keepers become the heroes or villains now.",
        "It'll be won and lost from the penalty spot.",
        "And here comes the shootout — hold your nerve.",
        "Penalties to decide it — the cruellest of arts.",
        "And the match's fate rests on twelve-yard kicks.",
        "A shootout, and only the brave will prosper.",
        "And it all boils down to penalties.",
        "We reach the spot kicks — the heart-stopping finale.",
        "And the lottery of penalties will name the winner.",
        "It's penalties — the moment every player dreads.",
        "And the showdown moves to the penalty spot.",
        "A shootout to settle a contest that deserved more.",
        "And the drama distils into single kicks from the spot.",
        "Penalties await, and the whole world holds its breath.",
        "And so to the spot — the shootout will have the final word.",
        "The toss is done and the shootout is set — this is it.",
        "And from the penalty arc, we find our winner.",
        "Spot kicks — the most brutal and beautiful of conclusions.",
        "And one by one, the players must face that walk to the spot.",
        "A penalty shootout — and every single kick will feel like an eternity.",
        "And so to this, the most nerve-shredding of finales.",
        "The spot is the judge, and it will give us a verdict shortly.",
        "And the goalkeepers are stepping up — this is their stage now.",
        "Penalties — and the only thing louder than the crowd is the silence before each kick.",
        "And the shootout begins — five kicks each, and a nation's fate on every one.",
        "The walls of this stadium close in as the penalty shootout is set up.",
        "And every player must summon everything they have for twelve yards of football.",
        "A shootout — and experience, composure, and a touch of luck will decide it.",
        "And so the match hands the final say to the penalty spot.",
        "Step up, breathe deep — it's a penalty shootout and it's here.",
        "And the drama reaches its absolute peak — spot kicks it is.",
        "One by one they'll step up, and one by one heroes will be made.",
        "And here we are — the shootout that everyone feared and nobody could avoid.",
        "The cruellest lottery in sport awaits — a penalty shootout.",
        "And the crowd can barely breathe as the shootout gets under way.",
    };

    private static readonly string[] ControversyLines =
    {
        "and there's real controversy here!",
        "and the protests are furious!",
        "and that decision will be talked about for days!",
        "and the players are surrounding the referee!",
        "and what a contentious moment that is!",
        "and the bench is up in arms!",
        "and there's uproar in the stands!",
        "and that's a hugely debatable call!",
        "and the referee has a storm on his hands!",
        "and the replays will not settle this one!",
        "and the indignation is plain to see!",
        "and that has caused absolute outrage!",
        "and the officials are under siege!",
        "and this is a flashpoint, no question!",
        "and there'll be plenty of arguments about that!",
        "and the crowd makes its feelings very clear!",
        "and that is a deeply controversial decision!",
        "and tempers are flaring all over the pitch!",
        "and the captain is remonstrating fiercely!",
        "and that one will divide opinion sharply!",
        "and the fourth official is getting an earful!",
        "and the sense of injustice is palpable!",
        "and the referee stands firm amid the fury!",
        "and what a talking point that has become!",
        "and the recriminations are flying!",
        "and that's a moment of pure controversy!",
        "and the whole ground is incensed!",
        "and the dissent is bubbling over now!",
        "and that decision has lit the touchpaper!",
        "and there's bedlam around the official!",
        "and the howls of protest ring out!",
        "and that call will dominate the headlines!",
        "and the players cannot believe the decision!",
        "and the controversy threatens to boil over!",
        "and the referee is the centre of a furious storm!",
        "and that's set the cat among the pigeons!",
        "and there are scenes of absolute uproar on the pitch!",
        "and the furious manager is off his bench in protest!",
        "and you could hear the gasps around the stadium!",
        "and that's a call that will haunt this match for years!",
        "and the assistant's flag has caused absolute pandemonium!",
        "and the referee is being surrounded by a dozen angry players!",
        "and tempers have well and truly frayed here!",
        "and both benches are now on their feet in disbelief!",
        "and that's an extraordinary decision by the man in the middle!",
        "and the protests spill from the pitch to the touchline!",
        "and you can understand every single complaint being made right now!",
        "and that is the sort of call that managers lose sleep over!",
        "and the visiting supporters are absolutely livid!",
        "and this is threatening to derail the entire match!",
        "and the official needs to restore order — and quickly!",
        "and even the most level-headed person in the ground is shaking their head!",
        "and the spark has been well and truly lit by that decision!",
        "and passions are running dangerously high on this pitch!",
        "and that's a decision that demands an explanation!",
        "and the debate in the commentary box is fierce — we can only imagine the pitch!",
        "and that could leave a very long shadow over tonight's result!",
    };

    private static readonly string[] DefensiveHowlerLines =
    {
        "a calamity at the back!",
        "an absolute shambles in defence!",
        "what a mix-up between the defenders!",
        "a horror show at the back!",
        "they've made a complete hash of that!",
        "a dreadful error at the heart of the defence!",
        "that's schoolboy defending!",
        "a catastrophic lapse from the back line!",
        "they've gifted it away with that blunder!",
        "an utter collapse in concentration there!",
        "a comedy of errors in their own half!",
        "they switched off completely — disaster!",
        "what a calamitous piece of defending!",
        "a shocking misjudgement at the back!",
        "they've been caught napping — woeful!",
        "an inexplicable error from the defender!",
        "the back line has gone to pieces!",
        "a catastrophe of their own making!",
        "they've conspired to make an awful mess of that!",
        "a defensive meltdown right there!",
        "that's a gift wrapped up at the back!",
        "what a way to lose your concentration!",
        "an embarrassing slip from the defence!",
        "they've left the door wide open — calamity!",
        "a dreadful mix-up has cost them dear!",
        "the defending there was non-existent!",
        "a moment of madness at the back!",
        "they've thrown caution and competence to the wind!",
        "an absolute clanger from the defender!",
        "the back four have been a shambles there!",
        "a careless, costly error at the back!",
        "they've gone walkabout in defence!",
        "what a glaring breakdown at the back!",
        "a self-inflicted wound of the worst kind!",
        "the defence has imploded in an instant!",
        "a hapless piece of defending, frankly!",
        "they've switched off at the worst possible time!",
        "the central defenders got in each other's way — what a mess!",
        "they've been carved open by their own indecision!",
        "that's the defending of a side with their nerves shredded!",
        "an absolute breakdown in communication at the back!",
        "they've handed the initiative straight back — criminal!",
        "the defenders lost the flight completely — a disaster!",
        "positional sense has entirely deserted them there!",
        "they've left a yawning gap and been punished for it!",
        "the last man was caught flat — poor, poor defending!",
        "that's the kind of mistake that changes the course of a match!",
        "caught in possession in their own box — you simply cannot do that!",
        "a total abdication of defensive responsibility there!",
        "they've given a mountain away with that individual howler!",
        "the back line parted like a curtain — completely unacceptable!",
        "a needless, reckless error that hands their opponents everything!",
        "the captain will be furious — that is simply not good enough!",
        "they forgot to track the runner and they've paid the ultimate price!",
        "a lapse of concentration at the most damaging moment possible!",
        "the covering defender just froze — and it's cost them dearly!",
        "an ugly, avoidable error and they will rue it deeply!",
    };

    private static readonly string[] KeeperHowlerLines =
    {
        "the goalkeeper will want to forget that!",
        "a real howler from the keeper!",
        "the goalkeeper has spilled it horribly!",
        "what a dreadful mistake from the keeper!",
        "the keeper has flapped at that one!",
        "an awful moment for the goalkeeper!",
        "the keeper let that squirm under him!",
        "a calamitous error from the goalkeeper!",
        "the goalkeeper has dropped a clanger!",
        "the keeper got it all wrong there!",
        "a nightmare for the goalkeeper!",
        "the keeper was caught completely flat-footed!",
        "the goalkeeper has fumbled it badly!",
        "what a glaring error between the sticks!",
        "the keeper should have done far better!",
        "the goalkeeper made a real meal of that!",
        "a costly misjudgement from the keeper!",
        "the goalkeeper rooted to his line — woeful!",
        "the keeper has palmed that straight out!",
        "an embarrassing fumble from the goalkeeper!",
        "the keeper has been beaten at his near post — poor!",
        "the goalkeeper got his angles all wrong!",
        "a horror moment for the man between the posts!",
        "the keeper let that one slip through his grasp!",
        "the goalkeeper completely misread the flight!",
        "what a shocker from the goalkeeper!",
        "the keeper will have nightmares about that!",
        "an unforgivable error from the goalkeeper!",
        "the goalkeeper came and missed it entirely!",
        "the keeper has thrown it into his own net — disaster!",
        "a moment to forget for the goalkeeper!",
        "the keeper was caught in no-man's-land!",
        "the goalkeeper has gifted them a chance!",
        "the keeper's hands let him down badly there!",
        "an absolute howler from the man in goal!",
        "the goalkeeper will be haunted by that one!",
        "the keeper misjudged the bounce — absolutely shocking!",
        "the goalkeeper came rushing out and got none of it!",
        "the keeper's positioning was all wrong and he's paid for it!",
        "he's spilled it straight into danger — the goalkeeper will not sleep tonight!",
        "the goalkeeper telegraphed the dive and guessed wrong!",
        "a sitter has gone past the keeper — he'll be devastated!",
        "the goalkeeping there was nothing short of catastrophic!",
        "the keeper was beaten far too easily at his near post!",
        "the goalkeeper had it in his hands and somehow let it go!",
        "a calamitous piece of goalkeeping that will be replayed endlessly!",
        "the keeper's footwork let him down and the result is a goal against!",
        "the goalkeeper was beaten by a shot he absolutely had to save!",
        "the keeper misjudged everything — the angle, the pace, the flight!",
        "the goalkeeper dived the wrong way and couldn't recover — dreadful!",
        "a fumble, a spill, and a goal — a nightmare sequence for the keeper!",
        "the goalkeeper sold himself far too early — and he's been punished!",
        "an error of judgement by the keeper that he will rue for a long time!",
        "the goalkeeper came for a cross he had no right to go for!",
        "he's parried it into his own net — as bad a moment as you'll see from a keeper!",
        "the man between the sticks had a moment of madness and his team have suffered!",
        "the goalkeeper lost concentration for a split second — and it's cost them a goal!",
    };

    private static readonly string[] Fillers =
    {
        "It's end to end here.",
        "The tempo has dropped.",
        "There's a lull in proceedings.",
        "The midfield battle is fierce.",
        "Both sides feeling each other out now.",
        "A real arm-wrestle in the centre of the park.",
        "The crowd is roaring them forward.",
        "A spell of pressure building here.",
        "The game has settled into a rhythm.",
        "There's some time-wasting creeping in.",
        "The pace is frenetic at the moment.",
        "A quieter passage of play now.",
        "The ball is being knocked around patiently.",
        "Tackles flying in all over the pitch.",
        "The atmosphere is simply electric.",
        "A cagey spell, this.",
        "The wind is swirling around the stadium.",
        "Both teams probing for an opening.",
        "The intensity has cranked right up.",
        "A breathless few minutes, that.",
        "The game is opening up nicely.",
        "Possession traded back and forth.",
        "The crowd grows restless during this lull.",
        "A bit of niggle entering the contest.",
        "The tempo lifts once more.",
        "Patient build-up from the back.",
        "The contest has gone a touch flat.",
        "Bodies on the line in this passage.",
        "The noise rises with every attack.",
        "A scrappy spell of play right now.",
        "The clock ticks on as the tension grows.",
        "Both sides catching their breath.",
        "The play is stretched from touchline to touchline.",
        "A few sloppy passes creeping in.",
        "The rain is starting to come down now.",
        "End-to-end stuff, and the crowd loves it.",
        "A momentary breather in a frantic match.",
        "The game is being fought in the trenches of midfield.",
        "Neither goalkeeper has been truly tested in this spell.",
        "The game ebbs and flows with no clear pattern.",
        "One side is dominating possession but struggling to create.",
        "The full-backs are driving forward at every opportunity.",
        "A yellow card keeps the passions in check — for now.",
        "The ball is doing the rounds at the back with little urgency.",
        "This is a classic cagey knockout-tie spell of play.",
        "Long throws and set-pieces are becoming the weapon of choice.",
        "The centre-forwards are feeding off scraps at the moment.",
        "The crowd has gone quiet — both sets of fans sense the danger.",
        "Free kicks are punctuating an increasingly fractious passage.",
        "Both midfields are cancelling each other out right now.",
        "A tactical battle developing here in the engine room.",
        "The pressing is relentless — neither side can settle on the ball.",
        "The wide men are getting isolated with nowhere to go.",
        "A sustained spell of keep-ball — patient, probing football.",
        "This is frantic, breathless, edge-of-your-seat stuff.",
        "The fourth official is getting very busy down that touchline.",
        "Corners, throw-ins, free kicks — the game is fragmenting.",
        "A fantastic counter-attack is thwarted at the last moment.",
        "The defensive lines are sitting deep and inviting pressure.",
        "The game stretches as both sides push for the decisive moment.",
        "Heads down, nerves jangling — this is pressure football at its rawest.",
        "A meaty challenge brings the crowd to its feet — no card given.",
        "The stadium holds its breath as the game teeters on a knife edge.",
        "One pass away from a chance — the tension is extraordinary.",
        "The wingers are getting the better of their markers in this spell.",
        "A backs-to-the-wall effort from one side as the other pours forward.",
        "The substitutes are warming up — changes could reshape this entirely.",
        "The pitch is cutting up and the ball is bouncing unpredictably.",
        "Sheer determination keeping one side in this match right now.",
        "The clock is becoming as important a factor as the football.",
        "Both benches are animated, urging their sides forward.",
        "A fascinating tactical adjustment being made on the fly here.",
        "The energy levels are dropping and legs are getting heavy.",
        "This is the kind of spell where one moment of magic could change everything.",
        "Wave after wave of attack, but the defence stands firm.",
        "The match has found a new gear and the fans are loving it.",
        "Bodies in front of every shot — defended magnificently in this spell.",
        "The duel in the middle of the park has been absorbing throughout.",
        "A breathless transition from defence to attack — thrilling football.",
        "The shape has held so far, but you sense something is about to give.",
    };

    private static readonly string[] AnalystAsides =
    {
        "You have to say, that was coming.",
        "That's where it's being won and lost.",
        "The legs are starting to go now.",
        "It's all about game management from here.",
        "You can see the fatigue setting in.",
        "The momentum has well and truly shifted.",
        "That's a tactical tweak paying off.",
        "They've lost their shape completely there.",
        "Game intelligence, pure and simple.",
        "The pressing has dropped off badly.",
        "That's where the space is opening up.",
        "They need to slow this right down.",
        "The full-backs are getting overrun.",
        "That's a masterclass in keeping the ball.",
        "They've gambled and left themselves exposed.",
        "The substitution has changed the picture.",
        "You'd take the draw if you were them now.",
        "They're inviting pressure onto themselves.",
        "That's experience telling in a big moment.",
        "The midfield's been bypassed far too easily.",
        "They've gone too long, too direct.",
        "It's a question of who blinks first now.",
        "The high line is asking for trouble.",
        "Concentration is everything at this stage.",
        "They've got numbers forward but no end product.",
        "That's where the game's being decided.",
        "The body language tells you everything.",
        "They've stopped trusting their passing.",
        "Composure is in short supply out there.",
        "That's a side hanging on for dear life.",
        "The width has dried up completely.",
        "They're a yard off the pace now.",
        "It's about managing the moment from here.",
        "They've surrendered the initiative cheaply.",
        "That's a team riding their luck.",
        "The transitions are killing them.",
        "Nerve and nous will settle this one.",
        "The defensive block is absolutely magnificent — disciplined and determined.",
        "They've turned this from a football match into a street fight — and it's working.",
        "The energy from the bench after that substitution is remarkable.",
        "Tactically, this is a real chess match and both managers are on top form.",
        "You cannot give that man a yard of space — and they just did.",
        "The tempo in the second period has been entirely different — credit to the manager.",
        "They've sat in and absorbed the pressure, and now they're dangerous on the break.",
        "The holding midfielder is doing a superb job shielding that back line.",
        "A team that believes, and belief is the most powerful thing in football.",
        "The pressing triggers are not being triggered — they've changed the system.",
        "You have to feel for that defensive line — they've been impeccable.",
        "The man-marking job on their playmaker has been utterly suffocating.",
        "Every header is being won, every second ball claimed — this is outstanding.",
        "The centre-backs are pushing higher and higher — it's a real gamble.",
        "They're playing the percentages and doing it very, very well.",
        "The captain is driving everyone around him — a colossal performance.",
        "Their compactness is making it almost impossible to play through them.",
        "The goalkeeper's distribution has unlocked several attacks already.",
        "They've done their homework — every run is being tracked and covered.",
        "When they win it back, they're devastating — the pace of those counter-attacks.",
        "The mental resilience this group has shown tonight is quite something.",
        "They've sat deep and invited the pressure because they knew it was the right call.",
        "The wingers have been given licence to run and they are exploiting it magnificently.",
        "One goal changes everything in this tie — and both sides know it.",
        "That positional switch has opened up a completely new dimension to this attack.",
        "The set-piece delivery has been second to none — a real weapon tonight.",
        "They've surrendered territorial advantage and it keeps biting them.",
        "The manager read this exactly right at half time — you can see the change.",
        "This is what elite defending looks like — brave, organised, relentless.",
        "The work rate of those forwards is extraordinary — closing down from the first second.",
        "They cannot afford another error — the margin for mistake is absolutely zero.",
        "The longer it stays level, the more the pressure shifts — fascinating dynamic.",
        "That's a team that has been drilled to within an inch of its life — and it shows.",
        "The quality on the counter is frightening — one of the best I've seen tonight.",
        "Patience. Organisation. Belief. That's what this side is built on right now.",
        "When the ball breaks loose in that area, there is only one team winning it.",
        "The emotional intelligence of the captain there — exactly what the moment demanded.",
        "They're conceding possession willingly to press high when the ball turns over.",
        "The number ten has dropped deep to collect and it's creating overloads everywhere.",
        "If they can keep that structure for another twenty minutes, they win this match.",
        "You can see the manager on the touchline — he's seen enough and he's going to act.",
    };

    /// <summary>Returns a scene-setting opener spoken before the fixture is named.</summary>
    public static string IntroOpener(ref Xoshiro256 rng) => IntroOpeners[rng.NextInt(IntroOpeners.Length)];

    /// <summary>Returns a kickoff line marking the start of the match.</summary>
    public static string Kickoff(ref Xoshiro256 rng) => KickoffLines[rng.NextInt(KickoffLines.Length)];

    /// <summary>Returns a line marking the restart for the second half.</summary>
    public static string SecondHalfStart(ref Xoshiro256 rng) => SecondHalfLines[rng.NextInt(SecondHalfLines.Length)];

    /// <summary>Returns a line marking the half-time whistle.</summary>
    public static string HalfTime(ref Xoshiro256 rng) => HalfTimeLines[rng.NextInt(HalfTimeLines.Length)];

    /// <summary>Returns a line marking the full-time whistle.</summary>
    public static string FullTimeWhistle(ref Xoshiro256 rng) => FullTimeLines[rng.NextInt(FullTimeLines.Length)];

    /// <summary>Returns a line announcing the start of extra time.</summary>
    public static string ExtraTimeStart(ref Xoshiro256 rng) => ExtraTimeLines[rng.NextInt(ExtraTimeLines.Length)];

    /// <summary>Returns a line introducing a penalty shootout.</summary>
    public static string ShootoutIntro(ref Xoshiro256 rng) => ShootoutLines[rng.NextInt(ShootoutLines.Length)];

    /// <summary>Returns a phrase highlighting a controversial incident.</summary>
    public static string Controversy(ref Xoshiro256 rng) => ControversyLines[rng.NextInt(ControversyLines.Length)];

    /// <summary>Returns a phrase describing a defensive blunder.</summary>
    public static string DefensiveHowler(ref Xoshiro256 rng) => DefensiveHowlerLines[rng.NextInt(DefensiveHowlerLines.Length)];

    /// <summary>Returns a phrase describing a goalkeeping error.</summary>
    public static string KeeperHowler(ref Xoshiro256 rng) => KeeperHowlerLines[rng.NextInt(KeeperHowlerLines.Length)];

    /// <summary>Returns a short ambient filler line observing the run of play.</summary>
    public static string Filler(ref Xoshiro256 rng) => Fillers[rng.NextInt(Fillers.Length)];

    /// <summary>Returns a colour-analyst interjection on tactics or game state.</summary>
    public static string AnalystAside(ref Xoshiro256 rng) => AnalystAsides[rng.NextInt(AnalystAsides.Length)];
}
