namespace WorldCup.Engine.Simulation;

using WorldCup.Engine.Random;

/// <summary>
/// Play-by-play announcer phrase catalogue covering match-flow moments:
/// scene-setting, period transitions, controversy, defensive errors,
/// ambient filler and colour-analyst asides.
/// </summary>
public static partial class CommentaryPhrases
{
    private static readonly string[] IntroOpeners =
    {
        "Good evening and welcome to a packed stadium",
        "Good evening and welcome, football fans the world over",
        "A warm welcome to you all on what promises to be a special night",
        "Welcome along to a stadium positively crackling with anticipation",
        "Good evening and a very warm welcome wherever you're watching from",
        "What an atmosphere already as we welcome you to tonight's showdown",
        "Hello and welcome to a cauldron of noise and colour",
        "A glorious evening here and the stage could not be better set",
        "Welcome one and all to a contest the whole world has been waiting for",
        "Good evening — the flags are flying and the anthems have barely faded",
        "Welcome to a night that could live long in the memory",
        "The tension is palpable as we welcome you to this one",
        "Good evening, and what a privilege it is to bring you tonight's drama",
        "Welcome along — the stands are a sea of colour from end to end",
        "A spine-tingling welcome to you all under the lights tonight",
        "Greetings from a stadium that is absolutely heaving",
        "Welcome to the showpiece — and you can feel the electricity",
        "Good evening from a ground bursting at the seams",
        "Hello and welcome to ninety minutes — perhaps more — of pure theatre",
        "Welcome along on a night thick with expectation",
        "A very good evening to you as the great occasion finally arrives",
        "Welcome to the big one — and there's a real edge in the air",
        "Good evening from pitchside, where the noise is already deafening",
        "Welcome, everybody, to a fixture dripping with history",
        "The scene is set, the crowd is roaring — welcome along",
        "Good evening and welcome to what should be a feast of football",
        "Hello and welcome — you join us on a truly unforgettable night",
        "Welcome to the heart of the action on a balmy evening",
        "Good evening — settle in, because this one has everything to live up to",
        "A wonderful welcome to you all from a sold-out arena",
        "Welcome along — the whole nation, both nations, hold their breath",
        "Good evening from a stadium shaking with anticipation",
        "Welcome to a night when reputations will be made",
        "Hello and welcome — the bunting is up and the dream is alive",
        "Good evening, and what a treat we have in store for you",
        "Welcome to the grand stage, where legends are forged",
    };

    private static readonly string[] KickoffLines =
    {
        "And the referee blows for the start — we're underway!",
        "We're off! The whistle goes and battle commences.",
        "And away we go — the match is alive!",
        "The referee gets us started and we are underway.",
        "Here we go then — the opening whistle has sounded!",
        "And it begins! The ball is rolling at last.",
        "We're up and running — game on!",
        "The whistle peeps and the contest is finally upon us.",
        "And they're off — the long wait is over!",
        "Underway at last — and the crowd lets out a roar.",
        "The referee signals and we have a football match!",
        "And the first touch is taken — we are live!",
        "Off they go — the journey begins right here.",
        "The shrill of the whistle, and we are away!",
        "And so it starts — let the drama unfold.",
        "We have lift-off — the match is in motion!",
        "The opening exchanges begin — we're underway!",
        "And the ball is in play — here we go!",
        "Kicked off and we're racing already.",
        "The referee's whistle cuts the air — game on!",
        "And we are off and running under the lights.",
        "There's the whistle — the action is finally here!",
        "Away we go, and you sense both sides mean business.",
        "The match springs into life — we are underway!",
        "And it's all systems go from the first whistle.",
        "The ball is struck and the contest has begun.",
        "Here we are then — the referee gets it all moving.",
        "And we're into it — no easing-in period here!",
        "The whistle blows, the crowd erupts, and we're away.",
        "And the great occasion is finally a football match!",
        "Off and rolling — the opening salvos are fired.",
        "The referee starts the clock and away we go.",
        "And there it is — the first whistle of the night!",
        "We are underway, and you can cut the tension with a knife.",
        "The ball is moving and so is this great occasion.",
        "And the dream becomes reality — we're underway!",
    };

    private static readonly string[] SecondHalfLines =
    {
        "We're back under way for the second half.",
        "And we're off again for the second forty-five.",
        "The second half is up and running.",
        "Back from the break, and the action resumes.",
        "The referee restarts and we're into the second half.",
        "And away we go once more — second half under way.",
        "Out they come, and the second period begins.",
        "Refreshed and reset, both sides resume the battle.",
        "The whistle goes and the second half is alive.",
        "And here we go again — forty-five more to play.",
        "Back to business as the second half kicks off.",
        "The second period is under way and the tempo lifts.",
        "We resume, and you sense a renewed urgency.",
        "And it's game on again after the interval.",
        "The teams re-emerge and the second half springs to life.",
        "Underway again — the closing act begins.",
        "And the second half gets going without delay.",
        "Back under the lights for the second forty-five.",
        "The referee signals and we're rolling once more.",
        "And we restart, the stakes higher than ever.",
        "The second half begins, and there's everything still to play for.",
        "Out of the blocks again as the second period starts.",
        "And we're away for the second half — buckle up.",
        "The interval is over and the contest reignites.",
        "Second half under way, and the crowd finds its voice again.",
        "And here we go for the run to the finish.",
        "The whistle peeps and the second half is on.",
        "Resumed, restarted, and right back into the fray.",
        "And the second half is upon us — no time to settle.",
        "Back into it, with the destiny of the match still open.",
        "The second period kicks off and the drama continues.",
        "And we're under way again — the decisive half awaits.",
        "Out they stride, and the second half roars into life.",
        "The action resumes — second half, here we come.",
        "And the closing forty-five is under way at last.",
        "Restarted, and the tension ratchets up another notch.",
    };

    private static readonly string[] HalfTimeLines =
    {
        "And that's the half-time whistle.",
        "The referee calls a halt — it's half time.",
        "And there's the whistle to end the first half.",
        "Time for a breather — that's half time.",
        "The first forty-five is up, and we pause.",
        "And the whistle sounds for the interval.",
        "Half time arrives, and there's plenty to chew over.",
        "The referee brings the half to a close.",
        "And that's it for the first period — half time.",
        "Whistle goes, and the players head for the tunnel.",
        "The first half is done and dusted.",
        "And we reach the interval at last.",
        "That'll be half time, and a chance to draw breath.",
        "The opening forty-five comes to an end.",
        "And there it is — the half-time break is upon us.",
        "The referee signals, and it's time for the team talks.",
        "Half time, and the tactics board will be busy.",
        "And the first half is brought to a close.",
        "The whistle peeps and we pause for the interval.",
        "That's the first half wrapped up.",
        "And off they go for a well-earned rest — half time.",
        "The referee ends the half, and there's lots to discuss.",
        "And we've reached the midway point of the match.",
        "Half-time whistle, and a moment to reflect.",
        "The first period closes, and the break begins.",
        "And that's the lot for the opening forty-five.",
        "Time called on the first half by the referee.",
        "And it's into the tunnel as half time arrives.",
        "The whistle goes — fifteen minutes to regroup.",
        "Half time, and both managers have thinking to do.",
        "And there's the break — the first act is complete.",
        "The referee whistles for the interval, right on schedule.",
        "And we pause the proceedings — that's half time.",
        "The first half signs off, and the break is here.",
        "And that's the half-time whistle, with much still to play for.",
        "Time for oranges and instructions — it's half time.",
    };

    private static readonly string[] FullTimeLines =
    {
        "It's all over! The final whistle has gone.",
        "And that's it — the referee blows for full time!",
        "The final whistle sounds — the match is done!",
        "It's finished! Full time at last.",
        "And there's the whistle — it's all over!",
        "The referee calls time, and the contest is complete.",
        "Full time! The drama has reached its conclusion.",
        "And that's the end — the final whistle has blown!",
        "It's over! Ninety-odd minutes come to a close.",
        "The whistle goes for the last time tonight.",
        "And there it is — full time, the match is settled.",
        "The referee ends it — and what a match it has been!",
        "Full time, and the final reckoning is in.",
        "And the curtain comes down — it's all over!",
        "The final whistle pierces the air — we're done!",
        "And that brings the contest to its end.",
        "It's finished! The referee blows the final whistle.",
        "Full time, and the players sink to the turf.",
        "And we've reached the end of the road — it's over!",
        "The whistle sounds, and the battle is concluded.",
        "And that's full time — the result is sealed.",
        "It's all over here, and what a journey it's been!",
        "The referee brings proceedings to a close at last.",
        "Full time! The dust settles on a memorable night.",
        "And there's the final whistle — the story is told.",
        "It's done and dusted — full time has arrived.",
        "The match reaches its conclusion with that whistle.",
        "And that's the end of it — the referee says no more!",
        "Full time, and the emotions pour out across the pitch.",
        "The final whistle goes — the verdict is delivered.",
        "And we've crossed the finish line — it's all over!",
        "The referee blows up, and the contest is history.",
        "Full time! Ninety minutes and more come to an end.",
        "And that is that — the final whistle has sounded.",
        "It's over at the last — the referee ends the game.",
        "And the match draws to its close — full time!",
    };

    private static readonly string[] ExtraTimeLines =
    {
        "We go to extra time.",
        "And it'll be settled in extra time.",
        "There's no separating them — extra time it is.",
        "We need an extra thirty minutes to find a winner.",
        "And so we head into extra time.",
        "Deadlocked at the end — on to extra time.",
        "It's level, and the additional period beckons.",
        "We can't be separated — extra time awaits.",
        "And the players brace themselves for extra time.",
        "No winner yet — we go to the extra half-hour.",
        "And it spills over into extra time.",
        "Locked together, so extra time will decide it.",
        "We push on into an additional thirty minutes.",
        "And there's more to come — it's extra time.",
        "Neither side could find a way through — extra time.",
        "And the contest extends into extra time.",
        "Tied at the finish, and now the extra period.",
        "We go again — extra time is upon us.",
        "And the drama stretches into extra time.",
        "Still all square, so we head for extra time.",
        "The match needs more — extra time it is.",
        "And weary legs must summon yet more — extra time.",
        "Nothing to choose between them, so extra time.",
        "And we're into the additional thirty minutes.",
        "It goes the distance — extra time now.",
        "And the marathon continues into extra time.",
        "We could not find a winner, so extra time arrives.",
        "And on we go — the extra period awaits.",
        "Level after ninety, and extra time will tell.",
        "We move to extra time to settle this.",
        "And the players gather themselves for extra time.",
        "It's all square, and extra time is the next chapter.",
        "And we head into the extra session.",
        "No breakthrough yet — extra time will decide.",
        "And the night gets longer — we go to extra time.",
        "Still deadlocked, and so extra time it must be.",
    };

    private static readonly string[] ShootoutLines =
    {
        "It will be settled from the penalty spot.",
        "And it comes down to penalties.",
        "There's nothing between them — a shootout will decide.",
        "We go to the lottery of spot kicks.",
        "And the drama heads to the penalty spot.",
        "It'll be decided from twelve yards.",
        "A shootout it is — nerves of steel required now.",
        "And the cruellest of finishes awaits — penalties.",
        "We can't separate them, so it's penalty kicks.",
        "And the tension cranks up — a shootout to come.",
        "It goes to penalties, and hearts are in mouths.",
        "The match will be settled in a shootout.",
        "And from the spot, the winner will be found.",
        "Penalties it is — the ultimate test of nerve.",
        "And we head for the most agonising of endings.",
        "It comes down to this — a penalty shootout.",
        "And destiny will be decided from twelve yards.",
        "A shootout beckons, and you can feel the dread.",
        "There's no other way — penalties will settle it.",
        "And the spot kicks will determine who goes through.",
        "We go to a shootout — pure theatre and torture.",
        "And the keepers become the heroes or villains now.",
        "It'll be won and lost from the penalty spot.",
        "And here comes the shootout — hold your nerve.",
        "Penalties to decide it — the cruellest of arts.",
        "And the match's fate rests on twelve-yard kicks.",
        "A shootout, and only the brave will prosper.",
        "And it all boils down to penalties.",
        "We reach the spot kicks — the heart-stopping finale.",
        "And the lottery of penalties will name the winner.",
        "It's penalties — the moment every player dreads.",
        "And the showdown moves to the penalty spot.",
        "A shootout to settle a contest that deserved more.",
        "And the drama distils into single kicks from the spot.",
        "Penalties await, and the whole world holds its breath.",
        "And so to the spot — the shootout will have the final word.",
    };

    private static readonly string[] ControversyLines =
    {
        "and there's real controversy here!",
        "and the protests are furious!",
        "and that decision will be talked about for days!",
        "and the players are surrounding the referee!",
        "and what a contentious moment that is!",
        "and the bench is up in arms!",
        "and there's uproar in the stands!",
        "and that's a hugely debatable call!",
        "and the referee has a storm on his hands!",
        "and the replays will not settle this one!",
        "and the indignation is plain to see!",
        "and that has caused absolute outrage!",
        "and the officials are under siege!",
        "and this is a flashpoint, no question!",
        "and there'll be plenty of arguments about that!",
        "and the crowd makes its feelings very clear!",
        "and that is a deeply controversial decision!",
        "and tempers are flaring all over the pitch!",
        "and the captain is remonstrating fiercely!",
        "and that one will divide opinion sharply!",
        "and the fourth official is getting an earful!",
        "and the sense of injustice is palpable!",
        "and the referee stands firm amid the fury!",
        "and what a talking point that has become!",
        "and the recriminations are flying!",
        "and that's a moment of pure controversy!",
        "and the whole ground is incensed!",
        "and the dissent is bubbling over now!",
        "and that decision has lit the touchpaper!",
        "and there's bedlam around the official!",
        "and the howls of protest ring out!",
        "and that call will dominate the headlines!",
        "and the players cannot believe the decision!",
        "and the controversy threatens to boil over!",
        "and the referee is the centre of a furious storm!",
        "and that's set the cat among the pigeons!",
    };

    private static readonly string[] DefensiveHowlerLines =
    {
        "a calamity at the back!",
        "an absolute shambles in defence!",
        "what a mix-up between the defenders!",
        "a horror show at the back!",
        "they've made a complete hash of that!",
        "a dreadful error at the heart of the defence!",
        "that's schoolboy defending!",
        "a catastrophic lapse from the back line!",
        "they've gifted it away with that blunder!",
        "an utter collapse in concentration there!",
        "a comedy of errors in their own half!",
        "they switched off completely — disaster!",
        "what a calamitous piece of defending!",
        "a shocking misjudgement at the back!",
        "they've been caught napping — woeful!",
        "an inexplicable error from the defender!",
        "the back line has gone to pieces!",
        "a catastrophe of their own making!",
        "they've conspired to make an awful mess of that!",
        "a defensive meltdown right there!",
        "that's a gift wrapped up at the back!",
        "what a way to lose your concentration!",
        "an embarrassing slip from the defence!",
        "they've left the door wide open — calamity!",
        "a dreadful mix-up has cost them dear!",
        "the defending there was non-existent!",
        "a moment of madness at the back!",
        "they've thrown caution and competence to the wind!",
        "an absolute clanger from the defender!",
        "the back four have been a shambles there!",
        "a careless, costly error at the back!",
        "they've gone walkabout in defence!",
        "what a glaring breakdown at the back!",
        "a self-inflicted wound of the worst kind!",
        "the defence has imploded in an instant!",
        "a hapless piece of defending, frankly!",
    };

    private static readonly string[] KeeperHowlerLines =
    {
        "the goalkeeper will want to forget that!",
        "a real howler from the keeper!",
        "the goalkeeper has spilled it horribly!",
        "what a dreadful mistake from the keeper!",
        "the keeper has flapped at that one!",
        "an awful moment for the goalkeeper!",
        "the keeper let that squirm under him!",
        "a calamitous error from the goalkeeper!",
        "the goalkeeper has dropped a clanger!",
        "the keeper got it all wrong there!",
        "a nightmare for the goalkeeper!",
        "the keeper was caught completely flat-footed!",
        "the goalkeeper has fumbled it badly!",
        "what a glaring error between the sticks!",
        "the keeper should have done far better!",
        "the goalkeeper made a real meal of that!",
        "a costly misjudgement from the keeper!",
        "the goalkeeper rooted to his line — woeful!",
        "the keeper has palmed that straight out!",
        "an embarrassing fumble from the goalkeeper!",
        "the keeper has been beaten at his near post — poor!",
        "the goalkeeper got his angles all wrong!",
        "a horror moment for the man between the posts!",
        "the keeper let that one slip through his grasp!",
        "the goalkeeper completely misread the flight!",
        "what a shocker from the goalkeeper!",
        "the keeper will have nightmares about that!",
        "an unforgivable error from the goalkeeper!",
        "the goalkeeper came and missed it entirely!",
        "the keeper has thrown it into his own net — disaster!",
        "a moment to forget for the goalkeeper!",
        "the keeper was caught in no-man's-land!",
        "the goalkeeper has gifted them a chance!",
        "the keeper's hands let him down badly there!",
        "an absolute howler from the man in goal!",
        "the goalkeeper will be haunted by that one!",
    };

    private static readonly string[] Fillers =
    {
        "It's end to end here.",
        "The tempo has dropped.",
        "There's a lull in proceedings.",
        "The midfield battle is fierce.",
        "Both sides feeling each other out now.",
        "A real arm-wrestle in the centre of the park.",
        "The crowd is roaring them forward.",
        "A spell of pressure building here.",
        "The game has settled into a rhythm.",
        "There's some time-wasting creeping in.",
        "The pace is frenetic at the moment.",
        "A quieter passage of play now.",
        "The ball is being knocked around patiently.",
        "Tackles flying in all over the pitch.",
        "The atmosphere is simply electric.",
        "A cagey spell, this.",
        "The wind is swirling around the stadium.",
        "Both teams probing for an opening.",
        "The intensity has cranked right up.",
        "A breathless few minutes, that.",
        "The game is opening up nicely.",
        "Possession traded back and forth.",
        "The crowd grows restless during this lull.",
        "A bit of niggle entering the contest.",
        "The tempo lifts once more.",
        "Patient build-up from the back.",
        "The contest has gone a touch flat.",
        "Bodies on the line in this passage.",
        "The noise rises with every attack.",
        "A scrappy spell of play right now.",
        "The clock ticks on as the tension grows.",
        "Both sides catching their breath.",
        "The play is stretched from touchline to touchline.",
        "A few sloppy passes creeping in.",
        "The rain is starting to come down now.",
        "End-to-end stuff, and the crowd loves it.",
        "A momentary breather in a frantic match.",
        "The game is being fought in the trenches of midfield.",
    };

    private static readonly string[] AnalystAsides =
    {
        "You have to say, that was coming.",
        "That's where it's being won and lost.",
        "The legs are starting to go now.",
        "It's all about game management from here.",
        "You can see the fatigue setting in.",
        "The momentum has well and truly shifted.",
        "That's a tactical tweak paying off.",
        "They've lost their shape completely there.",
        "Game intelligence, pure and simple.",
        "The pressing has dropped off badly.",
        "That's where the space is opening up.",
        "They need to slow this right down.",
        "The full-backs are getting overrun.",
        "That's a masterclass in keeping the ball.",
        "They've gambled and left themselves exposed.",
        "The substitution has changed the picture.",
        "You'd take the draw if you were them now.",
        "They're inviting pressure onto themselves.",
        "That's experience telling in a big moment.",
        "The midfield's been bypassed far too easily.",
        "They've gone too long, too direct.",
        "It's a question of who blinks first now.",
        "The high line is asking for trouble.",
        "Concentration is everything at this stage.",
        "They've got numbers forward but no end product.",
        "That's where the game's being decided.",
        "The body language tells you everything.",
        "They've stopped trusting their passing.",
        "Composure is in short supply out there.",
        "That's a side hanging on for dear life.",
        "The width has dried up completely.",
        "They're a yard off the pace now.",
        "It's about managing the moment from here.",
        "They've surrendered the initiative cheaply.",
        "That's a team riding their luck.",
        "The transitions are killing them.",
        "Nerve and nous will settle this one.",
    };

    /// <summary>Returns a scene-setting opener spoken before the fixture is named.</summary>
    public static string IntroOpener(ref Xoshiro256 rng) => IntroOpeners[rng.NextInt(IntroOpeners.Length)];

    /// <summary>Returns a kickoff line marking the start of the match.</summary>
    public static string Kickoff(ref Xoshiro256 rng) => KickoffLines[rng.NextInt(KickoffLines.Length)];

    /// <summary>Returns a line marking the restart for the second half.</summary>
    public static string SecondHalfStart(ref Xoshiro256 rng) => SecondHalfLines[rng.NextInt(SecondHalfLines.Length)];

    /// <summary>Returns a line marking the half-time whistle.</summary>
    public static string HalfTime(ref Xoshiro256 rng) => HalfTimeLines[rng.NextInt(HalfTimeLines.Length)];

    /// <summary>Returns a line marking the full-time whistle.</summary>
    public static string FullTimeWhistle(ref Xoshiro256 rng) => FullTimeLines[rng.NextInt(FullTimeLines.Length)];

    /// <summary>Returns a line announcing the start of extra time.</summary>
    public static string ExtraTimeStart(ref Xoshiro256 rng) => ExtraTimeLines[rng.NextInt(ExtraTimeLines.Length)];

    /// <summary>Returns a line introducing a penalty shootout.</summary>
    public static string ShootoutIntro(ref Xoshiro256 rng) => ShootoutLines[rng.NextInt(ShootoutLines.Length)];

    /// <summary>Returns a phrase highlighting a controversial incident.</summary>
    public static string Controversy(ref Xoshiro256 rng) => ControversyLines[rng.NextInt(ControversyLines.Length)];

    /// <summary>Returns a phrase describing a defensive blunder.</summary>
    public static string DefensiveHowler(ref Xoshiro256 rng) => DefensiveHowlerLines[rng.NextInt(DefensiveHowlerLines.Length)];

    /// <summary>Returns a phrase describing a goalkeeping error.</summary>
    public static string KeeperHowler(ref Xoshiro256 rng) => KeeperHowlerLines[rng.NextInt(KeeperHowlerLines.Length)];

    /// <summary>Returns a short ambient filler line observing the run of play.</summary>
    public static string Filler(ref Xoshiro256 rng) => Fillers[rng.NextInt(Fillers.Length)];

    /// <summary>Returns a colour-analyst interjection on tactics or game state.</summary>
    public static string AnalystAside(ref Xoshiro256 rng) => AnalystAsides[rng.NextInt(AnalystAsides.Length)];
}
