namespace WorldCup.Engine.Simulation;

using WorldCup.Engine.Random;

/// <summary>
/// Penalty-shootout and serious-injury play-by-play announcer phrase catalogue.
/// Partial of <see cref="CommentaryPhrases"/>. Each pool is a flat array of
/// spoken commentary fragments containing NO player names, team names or scores —
/// the caller layers those in around the chosen fragment.
/// </summary>
public static partial class CommentaryPhrases
{
    private static readonly string[] ShootoutOpeners =
    {
        "Twelve yards, and ice-cold nerves required.",
        "It all comes down to this — the cruellest way to settle it.",
        "Four hundred million people watching, and it boils down to one kick at a time.",
        "Here we go then — the lottery that isn't really a lottery at all.",
        "The longest walk in football starts here.",
        "Heroes will be made, and hearts will be broken, from the spot.",
        "Forty-five minutes, ninety, a hundred and twenty — and now it's down to this.",
        "The keepers step forward, the takers gather, and the agony begins.",
        "Everything they've worked for, distilled into a single swing of the boot.",
        "You can almost hear the heartbeats around this stadium.",
        "No more running, no more tackling — just the ball, the spot, and the nerve.",
        "The bravest game of all is about to be played.",
        "One by one they'll walk up, and one by one the tension will tighten.",
        "This is where legends are forged and reputations destroyed.",
        "The whole world leans in for the most excruciating finale football offers.",
        "A test of nerve like no other in the game.",
        "The tunnel of dread opens, and there's no way around it now.",
        "Composure is the only currency that counts from here.",
        "It's been a war of attrition, and now it's a duel of nerve.",
        "Twelve yards between glory and despair.",
        "The crowd falls into an uneasy hush as the shootout looms.",
        "Strap yourselves in — this is going to be unbearable.",
        "The coin is tossed, the ends are chosen, and the torture begins.",
        "Grown men can barely watch from the halfway line.",
        "The ultimate examination of a footballer's character starts now.",
        "Every kick from here will live with these players forever.",
        "The drama could not be wound any tighter than this.",
        "It's the moment nobody wants but everybody remembers.",
        "Steady hands, steady heads — and a great deal of luck.",
        "The shootout: where careers are defined in a heartbeat.",
        "A hush, then a roar, then a hush again — that's the rhythm to come.",
        "The managers can do nothing now but watch and pray.",
        "This is sport stripped right back to raw, naked nerve.",
        "The penalty spot has never looked so far away.",
        "Here it is — the part of the game that breaks the bravest of hearts.",
        "The arena holds its breath for the spot-kick showdown.",
        "Out they come, the men brave enough to take one.",
        "From here, it's a battle of wills, twelve yards at a time.",
        "The cruellest theatre in all of sport is about to begin.",
        "One kick can make you immortal — or haunt you for a lifetime.",
        "A deathly tension settles as the takers are chosen.",
        "Now we find out who can hold their nerve when it matters most.",
        "The whole tournament, the whole dream, comes down to this.",
        "Grown women and men alike cannot look — the dread is palpable.",
        "The goalkeepers are already doing their homework, pacing the line.",
        "Whoever holds their stomach together from here wins the shootout.",
        "Two sets of players, one spot, and all the nerve in the world required.",
        "The crowd can barely stand it, and the players look just the same.",
        "No tactic, no system, no formation — just boots, ball, and bottle.",
        "Players who have run miles tonight must now stand still and think clearly.",
        "The stadium has never been louder, and yet it feels strangely silent.",
        "Fortune favours the brave — but so does a well-placed penalty.",
        "The goalkeepers' moment to become legends is at hand.",
        "This is the most watched twelve yards of grass on the planet right now.",
        "The takers have been decided; now their characters will define the rest.",
        "Some of these penalties will be replayed on screens for decades.",
        "No hiding place, no teammate to share the burden — just the kick.",
        "One at a time they'll shoulder the weight of the whole summer.",
        "You train for this, you dream of this — and now it is terrifyingly real.",
        "The mind is the enemy here, not the goalkeeper.",
        "The crowd noise rises, then falls, then rises again — like breathing.",
        "Win or lose tonight could hinge on a single moment of calm.",
        "History is about to be written, twelve yards at a time.",
        "These players will remember every tiny detail of this moment forever.",
        "The spotlight has never been harsher nor the pitch so very long.",
        "A test of will, technique, and sheer bloody nerve — bring it on.",
    };

    /// <summary>Returns a tension-building opener spoken as a penalty shootout begins.</summary>
    public static string ShootoutOpener(ref Xoshiro256 rng) => ShootoutOpeners[rng.NextInt(ShootoutOpeners.Length)];

    private static readonly string[] ShootoutScoredBank =
    {
        "buries it, top corner!",
        "sends the keeper the wrong way and slots it home",
        "no hesitation — dispatched with absolute conviction",
        "right in the side netting, unstoppable",
        "smashes it down the middle as the keeper dives away",
        "tucks it calmly into the bottom corner",
        "rolls it home with ice in his veins",
        "drills it low and hard beyond the dive",
        "places it perfectly into the corner — flawless",
        "lashes it into the roof of the net",
        "keeps his nerve and finds the corner",
        "side-foots it past the keeper with total composure",
        "thumps it high into the net — emphatic",
        "fizzes it into the bottom corner, no chance for the keeper",
        "strokes it home as cool as you like",
        "powers it past the keeper's outstretched glove",
        "guides it into the corner with surgical precision",
        "rifles it into the top corner — magnificent under pressure",
        "sends the keeper one way and the ball the other",
        "crashes it into the net and lets out a roar",
        "dinks it down the middle — what audacity!",
        "finishes with the calm of a man on the training ground",
        "blasts it into the corner and the net bulges",
        "makes no mistake from twelve yards",
        "dispatches it with the swagger of a born finisher",
        "buries it low to the keeper's right",
        "slams it into the top bins, unreachable",
        "converts with absolute authority",
        "plants it firmly into the corner",
        "keeps it down and steers it past the dive",
        "hammers it home and points to the sky",
        "sweeps it into the net without a flicker of doubt",
        "strikes it true and the keeper never had a sniff",
        "tucks it away with nerveless precision",
        "drives it into the corner and turns away in triumph",
        "lifts it into the net as the keeper goes early",
        "finds the corner with a beautifully struck spot-kick",
        "thrashes it past the keeper — clinical from twelve yards",
        "rolls it into the empty corner, keeper sent the wrong way",
        "curls it just inside the post — unsavable",
        "smashes it home and beats his chest to the crowd",
        "places it inch-perfect beyond the despairing dive",
        "dispatches it coolly despite the weight of the world on his shoulders",
        "caresses it into the top corner — a thing of absolute beauty",
        "chips it cheekily down the middle as the keeper commits early — audacious!",
        "steps up and strokes it in as though it were a pre-match warm-up",
        "fires it low and hard to the right, never in doubt",
        "wrong-foots the keeper completely and slots it into the empty net",
        "arrows it into the top-right corner, unreachable from anywhere",
        "sends it across the keeper and into the far side-netting — perfect",
        "punches the air before it even hits the net — he always knew",
        "keeps his head down, picks his spot, and delivers with cold precision",
        "goes straight down the middle as the keeper dives to his left — brave",
        "curls it into the corner with the outside of his boot — pure class",
        "just lifts it over the outstretched glove and it nestles in the net",
        "plants it to the keeper's left and turns away before it even crosses the line",
        "thunders it into the bottom corner and the net snaps back violently",
        "a precise, composed finish — that never looked like missing",
        "steers it home with utter serenity, as though the world were not watching",
        "nestles it into the corner with a delicate side-foot — what poise",
        "powers it high and hard into the top bin — the keeper had no answer",
        "rolls it into the corner with a calm that borders on arrogance — sublime",
        "picks his side early and executes it flawlessly — that's a penalty of the highest order",
        "whips it into the corner and the net billows magnificently",
        "hits it with the precision of a sniper and the cool of an iceberg",
        "sends the keeper the wrong way with a subtle drop of the shoulder",
        "low and true, perfectly placed — the keeper was merely a spectator",
    };

    /// <summary>Returns a phrase describing a converted shootout penalty.</summary>
    public static string ShootoutScored(ref Xoshiro256 rng) => ShootoutScoredBank[rng.NextInt(ShootoutScoredBank.Length)];

    private static readonly string[] ShootoutMissedBank =
    {
        "skies it over the bar!",
        "off the post and away — agony!",
        "drags it horribly wide",
        "puts it into Row Z — what a moment to miss",
        "blazes it high over the crossbar",
        "smashes it against the bar and away to safety",
        "clatters the upright — and it stays out!",
        "scoops it well over — a dreadful miss",
        "pulls it wide of the far post",
        "rattles the woodwork and the chance is gone",
        "balloons it into the stands — heartbreak",
        "fires it wide of the upright — unbelievable",
        "slips as he strikes and screws it wide",
        "thumps it off the crossbar and over",
        "sends it sailing high and wide",
        "shanks it horribly off target",
        "hooks it past the post — a glorious chance squandered",
        "leans back and lashes it over the top",
        "wraps his foot around it and drags it wide of the post",
        "fluffs his lines and puts it well over the bar",
        "cannons it off the post and watches it bounce clear",
        "gets under it and balloons it into the crowd",
        "drives it miles over — he cannot believe it",
        "places it too close and clips the post — out it stays",
        "completely mishits it and it trundles wide",
        "smacks the bar and the ball bounces to safety",
        "sends it over and sinks to his knees",
        "misses the target altogether — sliced horribly wide",
        "strikes the upright and the rebound flies clear",
        "puts his spot-kick into the night sky",
        "hammers it onto the bar and the keeper breathes again",
        "drags his effort wide and holds his head in his hands",
        "blasts it over when he simply had to score",
        "clips the outside of the post — so close, yet no goal",
        "lifts it over from twelve yards — a moment to forget",
        "screws it wide of the left-hand upright",
        "hits it off the woodwork twice and out — cruel luck",
        "sends it spinning wide off the post",
        "scuffs it and the ball rolls apologetically wide",
        "thrashes it over the bar and the crowd groans as one",
        "smashes it against the angle of post and bar — out!",
        "sends it wide and the agony is written all over his face",
        "drags it across the face of goal and wide of everything",
        "stutters in his run-up and completely loses his conviction — well wide",
        "tries to place it and takes all the power off — rolls tamely wide",
        "sends it into the advertising hoardings — a truly dreadful penalty",
        "plants it firmly against the post and crumples to the turf",
        "clips the underside of the bar and it bounces down and out — no goal",
        "goes to the keeper's right but at a comfortable height — straight at him in the end",
        "goes for power and gets neither power nor direction — shanked horribly",
        "takes a long run-up, loses his nerve, and scoops it skyward",
        "the run-up is unconvincing and the outcome even more so — missed",
        "it hits the side-netting on the outside and hearts briefly soar, then sink",
        "mis-strikes it with the inside of his foot and it clangs the upright",
        "leans so far back he had no chance of keeping it down — up and over",
        "dummies his direction, picks the wrong corner, and the keeper saves — wait, no — it's wide!",
        "rakes it against the post and watches in horror as it bounces away",
        "a stutter-step in the run-up telegraphed everything — the keeper barely had to move",
        "toe-pokes it and the ball veers horribly off course — a wretched miss",
        "pushes it inches outside the right-hand post — agony, pure agony",
        "the ball is struck cleanly but aims straight at the keeper's midsection — saved? No — wide",
        "gets his standing foot wrong and slips at the crucial moment — miles off",
        "a wild, desperate hack that finds nothing but fresh air above the crossbar",
        "the ball seems to slow down in mid-flight and swerve wide at the last",
        "bites his lip as the shot clips the top of the bar and ricochets away",
        "the crossbar shakes, the crowd gasps, and the ball bounces well out — no goal",
        "it takes a cruel deflection off the turf and squirts wide — bad luck",
    };

    /// <summary>Returns a phrase describing a shootout penalty missed off target or off the woodwork.</summary>
    public static string ShootoutMissed(ref Xoshiro256 rng) => ShootoutMissedBank[rng.NextInt(ShootoutMissedBank.Length)];

    private static readonly string[] ShootoutSavedBank =
    {
        "SAVED! The keeper guesses right and flings out a strong hand!",
        "down low to his left — and he's kept it out!",
        "a colossal save — the gloves are the hero!",
        "SAVED! He reads it perfectly and gets down brilliantly!",
        "the keeper hurls himself to his right and claws it clear!",
        "what a stop — he's denied him from twelve yards!",
        "SAVED! Strong wrists turn it away to safety!",
        "the keeper stands tall and smothers it — magnificent!",
        "down he goes and the penalty is beaten away!",
        "SAVED! A heroic dive to keep it out!",
        "the keeper springs across and tips it onto the post!",
        "he picks the corner and gets a firm hand to it — saved!",
        "SAVED! The keeper has won this for his side!",
        "a fingertip is just enough to divert it wide!",
        "the keeper plunges full stretch and repels it!",
        "SAVED! He stayed big and the taker blinked first!",
        "the keeper guesses correctly and parries it clear!",
        "what a save — he read the run-up like a book!",
        "SAVED! Down to his right and a strong palm keeps it out!",
        "the keeper waits, waits, and then dives to deny him!",
        "a stunning reaction stop from the spot — saved!",
        "the keeper throws up an arm and blocks it brilliantly!",
        "SAVED! He gets down low and holds it firm!",
        "the keeper anticipates it and pushes it round the post!",
        "a save of immense bravery and timing — kept out!",
        "the keeper flies across his line and gets there — saved!",
        "SAVED! The keeper becomes the hero of the hour!",
        "he picked his side perfectly and made the stop!",
        "the keeper smothers it with his legs — what a save!",
        "SAVED! An outstanding low dive turns it aside!",
        "the keeper claws it away and the bench leaps as one!",
        "he gets a strong hand behind it and holds on — saved!",
        "SAVED! He denied him with nerve and a magnificent dive!",
        "the keeper guesses right and the spot-kick is foiled!",
        "down to his left and the penalty is repelled — heroics!",
        "the keeper produces a save out of the very top drawer!",
        "SAVED! He sprawled to his right and clawed it away!",
        "the keeper stands firm and parries it to safety!",
        "what a moment — the keeper has kept his side alive!",
        "SAVED! A brilliant, brave, decisive stop from the spot!",
        "the keeper reads it, dives, and gets a glove to it!",
        "he refused to move early and was rewarded — saved!",
        "the keeper denies him at the death and roars to the heavens!",
        "SAVED! He stood his ground and let the taker make the error!",
        "an outstretched boot gets the slightest touch and deflects it onto the post — saved!",
        "the keeper goes early but guesses right and the ball flies into his chest!",
        "he dives full-length to his left and palms it out — outstanding!",
        "SAVED! He barely moves and the taker puts it straight at him!",
        "the keeper roars his defiance, dives, and comes up with the ball!",
        "what composure from the keeper — he psyched him out and wins the duel!",
        "SAVED! He tips it over the bar with the very tips of his fingers!",
        "the keeper sells the dummy, holds his ground, and pushes it away!",
        "a two-handed save, parried to safety — the keeper was simply immense!",
        "SAVED! He flings himself to the far corner and it sticks!",
        "the keeper plants his feet, narrows the angle, and the taker cracks under the pressure!",
        "he gets a boot to it on the line and that is an extraordinary stop!",
        "SAVED! Textbook positioning, impeccable timing — a penalty-stopper's masterclass!",
        "the keeper stands like a colossus and the taker drives it straight at him!",
        "he anticipated it perfectly and the save looks almost routine — it was anything but!",
        "SAVED! The crowd erupts as the keeper springs to his right!",
        "a sprawling, barely-believable stop — the keeper has just done the impossible!",
        "he dives and catches it cleanly — he caught it! A clean take under the most intense pressure!",
        "SAVED! He guessed right, dived full length, and made himself a hero!",
        "the keeper stares down the taker, flinches not a muscle, then dives — perfection!",
        "saved at full stretch — he got a glove to it and clawed it to safety!",
        "SAVED! He wins the battle of wills and the whole ground knows it!",
        "the keeper produces something extraordinary — a save that will be talked about for years!",
    };

    /// <summary>Returns a phrase describing a shootout penalty saved by the goalkeeper.</summary>
    public static string ShootoutSaved(ref Xoshiro256 rng) => ShootoutSavedBank[rng.NextInt(ShootoutSavedBank.Length)];

    private static readonly string[] ShootoutPressureBank =
    {
        "This, to win the World Cup tie…",
        "Miss this and they're going home…",
        "The whole tournament on his shoulders now…",
        "Score, and they are through to the next round…",
        "Everything rides on this one swing of the boot…",
        "Get this wrong and it's all over for his side…",
        "This kick to keep the dream alive…",
        "Bury it, and the bench will spill onto the pitch…",
        "He must score, or it ends right here…",
        "The weight of a nation on this single penalty…",
        "This, to send them through and break a million hearts…",
        "No second chances now — it's score or go home…",
        "One kick from glory, one kick from despair…",
        "He has to find the net, or the journey ends…",
        "This penalty could win the whole thing…",
        "Convert, and they survive to fight another kick…",
        "Everything they've fought for comes down to this strike…",
        "Miss, and the agony of an early exit awaits…",
        "This, to make himself a hero forever…",
        "He knows what's riding on it — the whole world does…",
        "Score this and they march on; miss and they're done…",
        "The loneliest twelve yards in all of football, this…",
        "His entire tournament in the balance with this kick…",
        "This penalty to keep them breathing in the competition…",
        "Net it, and the celebrations will be wild…",
        "If he misses, it's heartbreak and the long road home…",
        "This is the kick that could decide everything…",
        "The pressure could not possibly be greater than this…",
        "He must hold his nerve, or it's curtains…",
        "This, to settle it once and for all…",
        "One mistake here and the dream dies…",
        "The whole stadium dares not breathe for this one…",
        "This kick carries the hopes of millions…",
        "Score and stay alive; miss and it's over…",
        "His country holds its breath for this single moment…",
        "This penalty to write his name into the history books…",
        "Bury this and they take an enormous step towards the next round…",
        "He simply cannot afford to miss this one…",
        "Everything has led to this — the loneliest of moments…",
        "This kick to break the deadlock and break some hearts…",
        "All eyes, all hopes, all fears — on this single penalty…",
        "He carries the burden of an entire campaign right now…",
        "Miss this, and a summer of dreams comes crashing down…",
        "This is the kick that separates the footnote from the legend…",
        "He knows the history; he's thought about nothing else since his name was called…",
        "Score this and they will name streets after him back home…",
        "There is no shared burden here — it's just him, alone, twelve yards from eternity…",
        "The keeper is dancing on the line, but all he can see is the back of the net…",
        "Miss it and the silence on the way back will be the longest of his life…",
        "This is the one. Everything before it was prelude. This is the penalty that matters…",
        "The whole tournament distilled into one swing of the boot…",
        "He walks up slowly, and every step feels like a mile…",
        "He's been here in his imagination a thousand times — now it's real…",
        "The keeper is trying every trick in the book, but the taker must blank it out…",
        "A nation of millions has gone completely still for this moment…",
        "If nerve could be measured, his would be tested to its absolute limit right now…",
        "Breathe, pick a corner, and trust yourself — that's all there is to it…",
        "Score, and the stadium lifts off its foundations…",
        "One penalty to decide a summer's work, a career's effort, a country's hope…",
        "He steps up, and the silence is deafening…",
        "History is watching every tiny detail of his run-up right now…",
        "Net this, and he will dream about it for the rest of his days — in the very best way…",
        "The goalkeeper gestures, the crowd swells, and he must shut it all out…",
        "The next few seconds will never leave him — whatever happens…",
        "One kick. One chance. Everything riding on it…",
        "He takes a deep breath at the top of his run-up, and the world holds its own…",
        "Every player on both benches has turned away or buried their head — all except him…",
    };

    /// <summary>Returns a high-pressure line spoken just before a decisive or must-score shootout kick.</summary>
    public static string ShootoutPressure(ref Xoshiro256 rng) => ShootoutPressureBank[rng.NextInt(ShootoutPressureBank.Length)];

    private static readonly string[] ShootoutSuddenDeathBank =
    {
        "Sudden death now — one blink and it's over.",
        "No margin for error any longer.",
        "Every kick a potential ending.",
        "We're into sudden death, where one miss is fatal.",
        "From here, a single slip decides the whole thing.",
        "Score and survive, miss and it's done — that's sudden death.",
        "The safety net is gone now; this is the high wire.",
        "One mistake from either side and the curtain falls.",
        "Sudden death — the cruellest twist in the cruellest contest.",
        "Now it's nerve against nerve, kick for kick, to the bitter end.",
        "Every penalty from here could be the last.",
        "We're beyond the regulation kicks — it's do or die.",
        "Each taker walks up knowing a miss ends it all.",
        "The tension is almost unbearable as sudden death begins.",
        "One slip, and a whole campaign evaporates.",
        "No room to breathe now — every kick is decisive.",
        "We've reached the part where heartbreak is one swing away.",
        "It's blow for blow now, and the next mistake is terminal.",
        "Sudden death — and you can scarcely watch.",
        "The margins have vanished; this is win or perish.",
        "From this kick on, there's no coming back from a miss.",
        "We're trading punches now, and one will land fatally.",
        "The pressure cranks to breaking point in sudden death.",
        "Score to stay alive — there is no other option now.",
        "Every walk to the spot could be the final one.",
        "It's nerve-shredding now: miss and the journey ends instantly.",
        "Sudden death, where the brave inherit everything.",
        "The slightest error and it's all over in a heartbeat.",
        "We go again, but now a single miss is decisive.",
        "This is football's most agonising form of Russian roulette.",
        "Kick for kick, heartbeat for heartbeat, until someone cracks.",
        "There's nowhere to hide in sudden death.",
        "One flinch, one flicker of doubt, and it ends.",
        "The takers know it — there is no tomorrow if they miss.",
        "Sudden death, and the whole world dare not look away.",
        "Now the smallest mistake carries the heaviest price.",
        "We're down to the wire — each kick could close the book.",
        "It's a duel to the last nerve now.",
        "Miss here and there is no reprieve whatsoever.",
        "The contest hangs by a thread with every single kick.",
        "Sudden death — where champions are separated from the rest.",
        "From now on, every penalty is a matter of life and death for the tie.",
        "One after another they go, and one of them will end it.",
        "The longer this goes, the more incredible it becomes.",
        "We are deep into uncharted territory — neither side will yield.",
        "Sudden death, and the goalkeepers now feel like the most important players on earth.",
        "One bad penalty and it's all done — that's the brutal maths of it.",
        "The crowd barely exhales between kicks; no one can take it much longer.",
        "You have to admire the nerve of every single taker stepping up now.",
        "One more miss and the handshakes begin; one more save and the same.",
        "This is extraordinary — still level, still alive, still terrifyingly tense.",
        "The keepers have become giants; the takers are walking into the unknown.",
        "Every conversion at this stage is an act of pure, magnificent courage.",
        "The managers have run out of plans — it's entirely in the players' hands.",
        "Each taker must silence the noise, silence the doubt, and simply strike the ball.",
        "History suggests someone will crack — the question is who, and when.",
        "We are in the realm of the unforgettable now.",
        "No cup final, no title race — nothing in football is quite like this.",
        "The players who haven't taken one are very grateful they haven't yet.",
        "Sudden death: the shootout's most brutal, honest, spectacular act.",
        "One mistake will end a World Cup campaign in an instant.",
        "It's beyond tactics, beyond fitness — it's raw human nerve against raw human nerve.",
        "The takers walk up alone, and return alone, in glory or in grief.",
        "We go again — the tension ratchets up another impossible notch.",
        "A miss at this stage would be devastating; a save, heroic beyond measure.",
        "History will remember who holds their nerve in this exchange.",
        "The whole crowd seems to be holding one enormous, collective breath.",
    };

    /// <summary>Returns a line spoken on entering or continuing sudden-death penalties.</summary>
    public static string ShootoutSuddenDeath(ref Xoshiro256 rng) => ShootoutSuddenDeathBank[rng.NextInt(ShootoutSuddenDeathBank.Length)];

    private static readonly string[] ShootoutWonBank =
    {
        "And that's it — they've done it from the spot!",
        "Pandemonium! They win the shootout and the bench empties!",
        "Heartbreak for one, ecstasy for the other.",
        "It's over — and the celebrations are utterly wild!",
        "They've won it! The keeper is mobbed by his teammates!",
        "And the shootout is settled — sheer, unbridled joy!",
        "That's the one! They march on and the dream lives!",
        "It's done — and there are grown men in tears all over the pitch!",
        "The agony and the ecstasy, side by side, in a single instant!",
        "They've held their nerve and they're through!",
        "And the whole squad sprints to celebrate as one!",
        "It's won and lost in the cruellest, most beautiful way!",
        "The decisive kick — and they have prevailed!",
        "Joy unconfined for one side, utter devastation for the other!",
        "And that settles it — they've come through the ordeal!",
        "The shootout is theirs — what scenes, what drama!",
        "They've done it the hard way, and the celebrations erupt!",
        "It's all over — and a wave of emotion sweeps the stadium!",
        "The winning kick is struck, and bedlam breaks loose!",
        "And the keeper falls to the turf as his teammates pile on!",
        "They survive the shootout — and the relief is overwhelming!",
        "That's the moment — they're through, and the party begins!",
        "Triumph and despair, separated by a single penalty!",
        "And they've won it from twelve yards — pure euphoria!",
        "The bench clears, the staff sprint on — they've made it!",
        "It's decided, and one side collapses in heartbreak while the other soars!",
        "They've come through the cauldron — and they are jubilant!",
        "And the final kick settles a contest for the ages!",
        "They win the shootout, and a nation can breathe again!",
        "Ecstasy at one end, inconsolable grief at the other!",
        "And that is that — they have won the shootout!",
        "The dream is alive — they've conquered the spot-kicks!",
        "It's theirs! The players race to the corner in delirium!",
        "And the heartache is total for the vanquished, the joy boundless for the victors!",
        "They've prevailed in the most nerve-shredding way imaginable!",
        "And so the shootout delivers its verdict — they go through!",
        "What a moment — they've won it, and the noise is deafening!",
        "It's over, and the emotions pour out in every direction!",
        "They've done it! Twelve yards from despair, and they've triumphed!",
        "And the shootout drama ends in scenes of wild celebration!",
        "The winning penalty — and the entire bench takes flight!",
        "They've held firm to the last, and the spoils are theirs!",
        "And it's settled — the cruellest contest hands them the sweetest of victories!",
        "And it's done! Players sprint from every corner of the pitch!",
        "The final kick and the whole place erupts — they're through!",
        "Tears of joy on one side, tears of something else entirely on the other.",
        "They've survived the lottery, and the relief is flooding out of every pore.",
        "That's it — and the manager is on his knees on the touchline!",
        "The winning penalty nestles in the net and a thousand dreams come true at once!",
        "And they go through! Months of preparation vindicated in one glorious moment!",
        "The goalkeeper is lifted off his feet by a mob of teammates — the hero of heroes!",
        "They've done it from the spot — the hard way, the nerve-shredding way!",
        "The net moves and the world changes in an instant!",
        "Scenes of pure delirium — this is why football is the greatest game!",
        "And the shoot-out delivers its final, beautiful verdict!",
        "The winning kick — and they pour onto the pitch in utter, joyous chaos!",
        "One side runs to the corner flag; the other stares at the turf. Football is merciless.",
        "They've marched through the crucible — and they march on to the next round!",
        "And it is done! A shootout to remember, and winners to cherish forever!",
        "The final penalty, and it goes in, and the night belongs to them!",
        "They stand at the summit of this shootout — and the joy is total!",
        "A moment of sporting theatre that will never, ever be forgotten!",
        "They're through — and somewhere a pundit is putting away the 'it's a lottery' take.",
        "It ends in the most dramatic way imaginable, and they are through!",
        "The winning side drops to their knees; the losing side does the same. Football does that.",
        "And on they go, into the next round, having survived the most intense examination of all!",
        "That is the moment — the one they will tell grandchildren about!",
    };

    /// <summary>Returns a line marking the moment a penalty shootout is decided.</summary>
    public static string ShootoutWon(ref Xoshiro256 rng) => ShootoutWonBank[rng.NextInt(ShootoutWonBank.Length)];

    private static readonly string[] SeriousInjuryReactions =
    {
        "Oh, that looks bad — you fear the worst with that one.",
        "He knew straight away; you could see it in his face. That could be months, not weeks.",
        "A horrible sight, and a real blow — his tournament may be over right there.",
        "That's a sickening one, and you don't want to see the replay.",
        "He's in real trouble here — that has the look of something serious.",
        "The way he went down tells you everything; that's not a knock, that's an injury.",
        "You hate to see it — the physios' faces say it all.",
        "That's the kind of moment that ends a player's summer in an instant.",
        "He's signalling to the bench already; he knows this is a bad one.",
        "I'm afraid that has the hallmarks of a serious one.",
        "The stretcher is coming, and that tells its own grim story.",
        "He's holding it and shaking his head — that is heartbreaking to watch.",
        "That looked like it went the wrong way; you fear ligaments there.",
        "A dreadful blow, and his face is a picture of pure anguish.",
        "He won't be continuing — and you suspect not for some time.",
        "That's a cruel, cruel moment for a player at the peak of a tournament.",
        "The silence around the ground tells you how serious this is.",
        "He's distraught, and so are his teammates gathered around him.",
        "That has the look of a fracture — you could almost hear it.",
        "His World Cup may have just ended in the most brutal fashion.",
        "You can see the medical staff are deeply concerned.",
        "That's an awful one, and there's no way he carries on after that.",
        "He's covering his face — he fears the worst, and so do we.",
        "A genuinely worrying sight, and the whole bench is on its feet.",
        "That kind of injury can take a player out for the best part of a year.",
        "He's being given oxygen — that's how serious this has become.",
        "The grimace tells you all you need to know; that's a bad one.",
        "Teammates are calling for help urgently — never a good sign.",
        "That's the injury every player dreads, and it's struck at the worst time.",
        "He's pounding the turf in frustration and pain — it's heartbreaking.",
        "I fear that's a long lay-off, possibly even longer.",
        "The physio isn't rushing the assessment — and that worries me greatly.",
        "He went into the challenge fine and came out of it in agony.",
        "That's a season-defining injury, and it's come from nowhere.",
        "You sense his tournament, perhaps more, has just been taken from him.",
        "The look on the manager's face says this one is serious.",
        "He can't put any weight on it at all — that's deeply concerning.",
        "A horrible, freak moment, and a player's dreams in tatters.",
        "That's not one he'll shake off; the stretcher confirms our fears.",
        "He's being carried off, and the applause is laced with real sympathy.",
        "I've seen that injury before, and it's rarely anything but serious.",
        "The whole stadium has gone quiet, and that says everything.",
        "A devastating blow — you wouldn't wish that on any player.",
        "The medical team are taking no chances — rightly so, this is a priority.",
        "His face is buried in his shirt; he knows precisely how serious this is.",
        "That's the kind of impact that reverberates around the whole stadium.",
        "There are no theatrics here — this is a player in genuine, considerable pain.",
        "He's been strapped up before, but his expression tells you this is different.",
        "The referee holds play immediately and signals with some urgency — this is bad.",
        "He hit the ground at a horrible angle; you can see the physio's concern from here.",
        "You can feel the collective wince from every supporter in this stadium.",
        "He'll want to carry on, but his body may not give him that option.",
        "He's asking the physio 'how bad?' — and the answer doesn't look reassuring.",
        "An innocuous-looking challenge, but the damage appears anything but innocuous.",
        "The game's biggest prize will have to wait — right now it's just about his wellbeing.",
        "Every player around him knows the feeling; none of them wants to see it happen here.",
        "Silence has replaced the noise, and that tells you all you need to know.",
        "The medical staff swarm around him, shielding the cameras as much as the player.",
        "He looked up at the sky and you could read the devastation in his expression.",
        "That's a worrying sign: he's pointing to his knee and shaking his head.",
        "The only thing that matters right now is that he receives proper care.",
        "His tournament instinct says get up; his body is saying something entirely different.",
        "A season's finest work may have just been cut heartbreakingly short.",
        "He's carried off to warm applause — and every fan, regardless of allegiance, joins in.",
        "The physio has seen enough — the stretcher is the correct call here.",
        "Those around him avert their eyes; only the medics need to look closely right now.",
        "A player of his quality deserves better than this — it's an awful moment to witness.",
    };

    /// <summary>Returns a colour-analyst reaction to an apparently serious injury such as a fracture or ligament damage.</summary>
    public static string SeriousInjuryReaction(ref Xoshiro256 rng) => SeriousInjuryReactions[rng.NextInt(SeriousInjuryReactions.Length)];
}
