using WorldCup.Engine.Random;

namespace WorldCup.Engine.Simulation;

/// <summary>
/// Provides randomly selected, name-free commentary fragments describing on-field
/// flashpoints between players and benches, escalating from harmless handbags through
/// full brawls to the referee restoring order. Each fragment is a self-contained
/// broadcast phrase containing no player names, team names, or scores so the generator
/// can supply that context around it.
/// </summary>
public static class ConfrontationNarratives
{
    /// <summary>
    /// Minor, almost comic pushing and chesting that fizzles out to nothing.
    /// </summary>
    private static readonly string[] HandbagsBank =
    {
        "a bit of handbags, nothing more",
        "chest-to-chest, foreheads almost touching, but it's all front",
        "a shove and a sneer — handbags at dawn",
        "all puffed-out chests and nobody actually swinging",
        "a half-hearted push in the back, and that's about the size of it",
        "plenty of posturing, not a lot of punching",
        "they bump chests, peacocking, and then think better of it",
        "a flick of the hand, a roll of the eyes — pure theatre",
        "a token little shove that wouldn't disturb a feather",
        "the two of them squaring up like it's the playground",
        "a bit of pushing and shoving that fizzles out almost instantly",
        "all mouth and no menace — classic handbags",
        "a gentle barge and a wagging finger, nothing in it really",
        "they grab each other's shirts and then sheepishly let go",
        "more huff and puff than genuine aggro",
        "a cartoonish little dust-up, both of them playing to the gallery",
        "a nudge, a nudge back, and it peters out",
        "shirt-tugging and tutting — it's all very polite, really",
        "a bit of argy-bargy, but you sense their hearts aren't in it",
        "they lean into one another, neither prepared to actually do anything",
        "a comedy shove and an even more comedic stagger back",
        "a flap of the arms, a bit of chuntering, and it's done",
        "the softest of pushes, met with the most theatrical of falls",
        "a quick chest-bump and they're already backing away",
        "minor handbags — the sort that's forgotten in seconds",
        "they jostle and grumble, but it never threatens to ignite",
        "a feeble little prod and an even feebler response",
        "all bristle and no bite, the pair of them",
        "a bit of finger-pointing and pantomime outrage",
        "they square up, realise the camera's on them, and ease off",
        "a playful-looking shove that's gone almost before it started",
        "hand on the chest, hand on the chest back — and that's your lot",
        "a little flurry of pushing that wouldn't trouble a turnstile",
        "they make a show of it, but there's nothing behind the bluster",
        "barely a ripple — handbags, and weak ones at that",
        "a token barge, a token glare, and on we go",
        "a fuss about nothing, the two of them quickly thinking better of it",
        "two players bumping shoulders and then immediately backing off",
        "a theatrical stagger and a wagging finger — classic wind-up merchant stuff",
        "a gentle prod in the ribs, met with an exaggerated howl of protest",
        "they collide, both go wide-eyed, and then nothing materialises",
        "a token shove from behind that barely registers",
        "they square up briefly, then both seem to remember the cameras",
        "a petulant little barge and an even more petulant response",
        "arms thrown wide, palms up, playing the innocent — pure handbags",
        "a tap on the back of the head, more annoying than dangerous",
        "a barely-there shove disguised behind a wall of indignation",
        "they bicker and bristle but nobody actually does anything",
        "a flicker of aggression that vanishes the moment the ref looks over",
        "a sarcastic round of applause and a dismissive wave — handbags through and through",
        "the pair of them flexing and posturing without the slightest intention of following through",
        "a bump of shoulders, a cold stare, and then both walk away",
        "a tug on the sleeve, a shake of the arm, and it's done in seconds",
        "they jaw at each other from two yards apart and then drift off in opposite directions",
        "two players in each other's faces, playing to the crowd, doing nothing else",
        "the faintest of shoves, the loudest of reactions — he'll be embarrassed watching that back",
        "arms spread wide, inviting a reaction, and getting absolutely none",
        "a half-hearted grapple that both of them seemed keen to escape from",
        "they bump foreheads, theatrically of course, and then laugh it off",
        "a desultory push and a desultory push back — no harm, no foul",
        "fingers pointed, voices raised, but their feet barely moved an inch",
        "a huff and a puff and a lot of theatre — handbags, nothing more",
        "they make a fuss, the ref intervenes, and both look slightly sheepish",
        "a shove in the chest met with a shrug — this one's already over",
        "all the body language of a fight, none of the actual intent",
        "a petulant kick at a divot rather than at anyone — sums it up perfectly",
    };

    /// <summary>
    /// Two players squaring up nose to nose, with words exchanged and the temperature rising.
    /// </summary>
    private static readonly string[] FaceOffBank =
    {
        "nose to nose now, and the words are flying",
        "eyeball to eyeball, neither willing to back down",
        "a finger jabbed into the chest, and it's getting heated",
        "they're right up in each other's faces, foreheads almost meeting",
        "toe to toe, jaws jutting, and the language is colourful",
        "a real stand-off — chins up, stares locked",
        "they square up properly, chest puffed against chest",
        "you can see the words being spat between them",
        "neither one taking a backward step here",
        "snarling at each other from inches apart",
        "a proper face-off, the pair of them bristling",
        "they lock eyes and the temperature has rocketed",
        "an aggressive prod to the shoulder, and the staring contest begins",
        "they go nose to nose, daring the other to make the first move",
        "jabbing fingers and bared teeth — this is simmering",
        "a long, hostile stare and plenty being said",
        "they front up to one another, neither blinking",
        "right in his grill, mouthing off, refusing to give an inch",
        "the two of them squared up, chests heaving, words exchanged",
        "a venomous little exchange, faces just inches apart",
        "they're squaring up like a couple of boxers at the weigh-in",
        "shoulders back, chins forward, the stare-down is on",
        "a hostile face-off, jaws working overtime",
        "they get nose to nose, and you can lip-read most of it",
        "a finger in the face and a mouthful to go with it",
        "neither prepared to drop the gaze — this is brewing",
        "they front up, eyeballs out, the words getting nastier",
        "a real eyeball-to-eyeball confrontation now",
        "chest against chest, foreheads down, and the chuntering builds",
        "they square off, both jabbing, both refusing to step away",
        "a pointed finger, a curled lip, and the heat is rising fast",
        "the two of them locked in a furious stare, mouths going",
        "noses almost touching, voices rising — this could boil over",
        "they front each other up, neither giving the other the satisfaction",
        "a proper squaring-up, both of them spoiling for it",
        "an angry face-off, fingers prodding, words sharpening",
        "eye to eye, breath to breath, and it's turning ugly",
        "jaws clenched, eyes burning, the two of them locked in silent fury",
        "they march straight up to one another, not a flicker of backing down",
        "a long, slow walk into each other's personal space — nobody blinked",
        "both of them straining forward, the gap between them almost nothing",
        "a pointed finger an inch from the nose — this is really bubbling now",
        "they find each other's eyes and neither one looks away",
        "neck veins out, chins thrust forward — this is a proper stand-off",
        "a furious mouthing-off, faces pressed close, the air between them thick",
        "chests pumping, hands gesturing wildly, the words getting personal",
        "they meet in the middle of the pitch and neither one gives ground",
        "a cold, hard stare from inches apart — temperature through the roof",
        "foreheads almost touching as the shouting gets louder",
        "they square right up, daring each other to make something of it",
        "an icy face-off — these two clearly have history",
        "eyes locked, teeth bared, the words coming fast and furious",
        "they walk towards each other with real purpose, and it's getting tense",
        "a stare-down that seems to last an age, neither man blinking",
        "chests out, shoulders set, the pair of them absolutely seething",
        "a volcanic face-off, fingers jabbing, heads almost butting",
        "they confront each other properly now, foreheads inches apart",
        "a ferocious glare and a torrent of words — this is nastier than it looked",
        "they stride towards one another and nobody within ten yards wants to be involved",
        "both of them furious, noses nearly touching, voices rising sharply",
        "a simmering row that's finally boiled over into a proper nose-to-nose",
        "they get right up in each other's face and the words are flying",
        "eyes narrowed, faces close, and the language wouldn't make the highlights reel",
        "a taut, bristling face-off, both refusing to give an inch",
        "they confront each other eyeball to eyeball, and the crowd has gone quiet",
        "a real up-and-under of words and stares — properly intense now",
    };

    /// <summary>
    /// A genuine shoving match that drags more and more players into the middle.
    /// </summary>
    private static readonly string[] ShovingBank =
    {
        "and now there's a melee — players piling in from everywhere",
        "a proper shoving match, bodies flying into the mix",
        "it's kicked off — half a dozen players grappling",
        "shirts being grabbed, players shoved this way and that",
        "a real scuffle now, more and more of them wading in",
        "pushing and barging, the crowd around the ball swelling",
        "they're shoving each other hard, and others are joining in",
        "a scrum of bodies, everyone trying to get a piece of it",
        "players streaming in to shove and be shoved",
        "a heaving mass of players, plenty of pushing going on",
        "it's getting physical — shirts pulled, shoulders barged",
        "a proper grappling match breaking out in the middle",
        "shoves landing, players stumbling, a real tangle now",
        "bodies piling in, hands on chests, everyone having a go",
        "a knot of players shoving and jostling, tempers up",
        "the pushing has spread — six, seven players in the thick of it",
        "a genuine scuffle, players being barged off their feet",
        "they're wrestling and shoving, the whole thing snowballing",
        "a chaotic little maul, players shoving from all angles",
        "shirts stretched, shoulders flying — this is a proper shoving match",
        "more bodies pouring in, the shoving intensifying",
        "it's a tangle of limbs, everyone pushing somebody",
        "a real ruck of players, barging and grappling",
        "the scuffle's grown — players being dragged and shoved around",
        "hands shoving faces away, players piling into the middle",
        "a heaving scrum of shoving and shirt-pulling",
        "players being flung aside as more wade into the scuffle",
        "a genuine grapple now, bodies crashing together",
        "the shoving match is pulling in everyone within reach",
        "shoulders and chests barging, players tumbling into one another",
        "it's a free-for-all of pushing and pulling out there",
        "a swelling melee, players shoving with real intent",
        "they're grappling and barging, the whole pack of them",
        "a proper scrap of shoving, players stumbling over each other",
        "bodies hurled into the mix, the pushing getting fiercer",
        "a churning knot of players, all shoving, all jostling",
        "the scuffle's well and truly on — players grappling everywhere",
        "a rolling tangle of players, the shoving getting more forceful",
        "they shove each other hard and suddenly five more pile in",
        "a violent jostle that sucks in players from both ends of the pitch",
        "shirts ripped, boots stamping — this shoving match has real teeth",
        "a surging push-and-shove, players stumbling into one another from all sides",
        "a heated grapple that multiplies by the second as more join in",
        "it starts with one shove and within moments half the pitch is involved",
        "players barged off the ball, retaliating, and the thing snowballs instantly",
        "a proper wrestle breaking out, players grabbing and dragging each other",
        "both sets of players converging, and it's getting rough in the middle",
        "an ugly, lurching shove-fest, more and more bodies joining the pile",
        "a rampant scuffle, players barging from every angle",
        "they grapple and strain, teammates dragging them apart even as others wade in",
        "the shoving has gone circular — nobody can quite reach who they're after",
        "a rough-and-tumble of pushing players, all swirling around one flashpoint",
        "players yanking at shirts, shoving shoulders, the scrum growing by the second",
        "a mob of grappling players, none of them making it look pretty",
        "they shove each other hard, and suddenly it's bodies everywhere",
        "a messy, churning shoving match, players stumbling and regrouping",
        "an erupting shoving melee that seems to draw in everyone on the pitch",
        "a proper scramble, players shoving and grabbing in a frantic tangle",
        "the shoving spreads outward like a ripple — five in, then ten",
        "a swelling, angry scrum of players all jostling for position",
        "shirts hauled, elbows flying, the shoving match well and truly on",
        "a heaving mass of players locked in pushing and shoving",
        "the shoving intensifies with every second as more get involved",
        "they barge and wrestle, neither side backing down an inch",
        "a raucous, swirling shove-fest, the ref nowhere near it yet",
        "a real rumpus of pushing bodies, the shoving pulling in the whole squad",
    };

    /// <summary>
    /// A serious, ugly brawl with many players involved that has badly boiled over.
    /// </summary>
    private static readonly string[] MassConfrontationBank =
    {
        "this has completely boiled over — a full-scale melee in the corner",
        "an ugly, ugly scene, players being dragged apart",
        "absolute chaos — this is the last thing the tournament needed",
        "it's a full-blown brawl now, bodies everywhere",
        "this is dreadful — a mass confrontation, players swarming in",
        "an enormous melee, and it's turned genuinely nasty",
        "players grabbing players, a horrible tangle of bodies",
        "this is a disgrace — a huge, ugly free-for-all",
        "a sprawling brawl, fists and shoves flying in the chaos",
        "the whole thing has erupted — players piling in from every direction",
        "an almighty melee, and tempers have completely snapped",
        "this is bedlam — a full-scale confrontation engulfing the pitch",
        "an ugly mass of bodies, players being hauled out by their shirts",
        "it's gone completely — a vicious, swirling brawl",
        "a horrible scene, players grappling and grabbing en masse",
        "this has boiled right over — a serious, ugly confrontation",
        "a full-on melee, and it's getting more violent by the second",
        "players everywhere, shoving, grabbing, dragging — total mayhem",
        "an enormous, ugly pile-up of players, and it's turning sour",
        "this is exactly what nobody wanted — a mass brawl in full flow",
        "a swirling sea of bodies, players hurling each other around",
        "it's anarchy out there — a huge confrontation, nobody backing off",
        "an ugly mob of players, fists clenched, shoves landing",
        "a vicious melee, and the stewards must be dreading this",
        "the whole squad of them piling in — this is a proper brawl",
        "players locked together in an ugly, heaving mass",
        "a serious confrontation now, players being prised apart one by one",
        "this is shameful — a full-scale brawl in front of a global audience",
        "an enormous flashpoint, players streaming in to join the fight",
        "it's boiled over completely — a churning, furious mob",
        "a horrible, ugly melee, and it shows no sign of calming",
        "players grabbing throats and shirts in a sprawling brawl",
        "this is as ugly as it gets — a mass of grappling bodies",
        "a vicious, swirling confrontation, players hauled out by teammates",
        "the whole pitch seems to have converged — an almighty brawl",
        "an ugly scrum of fury, players being dragged clear by the collar",
        "it's erupted into a full brawl — an awful look for the game",
        "an enormous wave of bodies converging — this is truly out of hand",
        "a nightmarish scene, players swarming from every corner of the pitch",
        "this has turned into a full-scale confrontation, and it's deeply unpleasant",
        "players rushing in from fifty yards away — nobody is staying out of this",
        "a boiling mass confrontation, the pitch barely visible through the bodies",
        "players piled into each other in one enormous, seething knot",
        "this is a genuinely horrible scene — a mass melee with no sign of stopping",
        "both squads fully involved now, grappling and grabbing from all directions",
        "a swirling storm of bodies — this is everything football doesn\'t want",
        "a sprawling, ugly confrontation that has engulfed most of the pitch",
        "players locked together in a horrible, heaving mass — this is very bad",
        "a mass flare-up, bodies grappling, voices roaring, the whistle going constantly",
        "every outfield player converging into one furious, tangled mob",
        "this has boiled over completely and it is an awful, ugly spectacle",
        "a vicious, swirling brawl with players being dragged off by their collars",
        "a horrible ripple of confrontation has become a full tidal wave",
        "both sets of players in one enormous, writhing scrum — truly shocking",
        "this is a mass brawl in the proper sense — nobody backing off, nobody calm",
        "an entire pitch worth of players cramming into one furious flashpoint",
        "a chaotic, sprawling mass confrontation — the referee is powerless for now",
        "players being hurled and shoved in every direction — bedlam",
        "this has deteriorated rapidly into an ugly, shameful mass brawl",
        "an enormous confrontation, players from both sides piling into the centre",
        "a flashpoint that has become a full-scale melee in the space of seconds",
        "a horrible, churning mob of players — this tournament didn\'t need this",
        "the pitch is a sea of clashing bodies — this is completely out of control",
        "a real mob scene, players grappling in every direction",
        "a mass confrontation unlike anything seen in this tournament so far",
        "an appalling spectacle — the whole pitch has turned into one enormous brawl",
    };

    /// <summary>
    /// The benches, substitutes, and staff spilling onto the pitch to join the trouble.
    /// </summary>
    private static readonly string[] BenchInvolvedBank =
    {
        "and now the benches have emptied — staff and subs sprinting on!",
        "the technical areas have cleared, coaches wading in to drag their players out",
        "substitutes pouring onto the pitch — this is bedlam on the touchline",
        "the benches are emptying, subs charging onto the field",
        "staff and substitutes streaming on — this is completely out of hand",
        "the dugouts have emptied, everyone sprinting into the fray",
        "subs in their bibs racing on to join the confrontation",
        "the whole bench is up and onto the pitch now",
        "coaching staff and subs flooding on — utter chaos",
        "the touchline has emptied, bodies pouring onto the field",
        "substitutes hurdling the advertising boards to get involved",
        "physios, subs, coaches — the lot of them are on the pitch",
        "both benches have cleared, and it's mayhem out there",
        "the reserves are charging on, fuelling the confrontation",
        "staff sprinting from the dugout to haul their players away",
        "the subs have piled on, and now it's truly enormous",
        "the technical area's deserted — everyone's in the middle of it",
        "bench players in bibs wading into the brawl",
        "the dugouts have emptied as one — players streaming on",
        "kit men and coaches dragged into the chaos by their own players",
        "the entire bench up and racing onto the field",
        "subs and staff flooding on, the trouble doubling in size",
        "the touchline's gone — everyone has spilled onto the pitch",
        "substitutes sprinting on, some to fight, some to drag others off",
        "the benches have well and truly emptied now",
        "coaching staff charging across the turf to break it up",
        "a wave of subs and staff pouring off both benches",
        "the dugout's cleared — bib-wearing subs piling into the scrum",
        "everyone from the bench is on, and it's turned into bedlam",
        "the touchline staff have abandoned their posts and run on",
        "subs streaming over the line, the confrontation swelling massively",
        "the whole matchday squad seems to be on the pitch now",
        "benches emptied, staff and players tangled together in the chaos",
        "substitutes vaulting the boards, racing to join the melee",
        "the technical areas have spilled onto the field — pure chaos",
        "every last sub and coach is out there now — extraordinary scenes",
        "the benches have erupted, bodies flooding onto the pitch",
        "the subs can\'t help themselves — they\'re over the boards and on the pitch",
        "the coaching staff have abandoned the dugout and gone straight into the thick of it",
        "bench players in training tops sprinting sixty yards to join the fray",
        "the whole technical area has emptied in a flash — this is enormous now",
        "substitutes and staff streaming onto the field, doubling the chaos",
        "both benches off as one — it\'s a full-on invasion of the pitch",
        "subs who haven\'t kicked a ball all night are suddenly in the middle of it",
        "the dugouts spill their contents — every body is out there",
        "bib-wearing substitutes hurtling past the corner flag to get involved",
        "the equipment staff have even piled on — this is truly extraordinary",
        "the coaching team charge on in a pack, heading straight for the melee",
        "an avalanche of subs and staff from both benches onto the pitch",
        "the fourth official trying in vain to prevent the exodus from the benches",
        "the technical areas empty simultaneously — this is a full-scale invasion",
        "physiotherapists, kit men, and coaches all drawn into the chaos",
        "subs sprinting the length of the touchline to reach the confrontation",
        "every single warm-up jacket on both benches is now on the pitch",
        "the coaching staff charge on in a wave, some to help, some to inflame it",
        "the dugouts have well and truly emptied — an extraordinary, chaotic scene",
        "substitutes who were due on in ten minutes are now in the middle of a brawl",
        "bench staff flooding onto the field, the confrontation swelling dramatically",
        "the subs hurdle the advertising boards without breaking stride",
        "coaching staff can\'t hold their players back — so they\'ve joined them",
        "a stampede from both technical areas onto the pitch",
        "every bib in both squads is suddenly on the field of play",
        "the reserves pour on, drawn in by the chaos like a magnet",
        "kit men and analysis staff dragged into the melee as the benches empty",
        "the touchline completely abandoned as both sets of staff charge on",
        "a full exodus from the technical areas — this scene is completely out of hand",
    };

    /// <summary>
    /// The managers and coaching staff squaring up at one another on the touchline.
    /// </summary>
    private static readonly string[] TouchlineRowBank =
    {
        "the two dugouts going at it now — the managers nose to nose",
        "fourth official caught in the middle of a touchline row",
        "the managers squaring up in the technical area",
        "a furious touchline row — the two bosses jabbing fingers",
        "the coaching staff of both sides at each other on the sideline",
        "the managers eyeball to eyeball, the fourth official powerless",
        "a proper set-to in the technical areas, the bosses bristling",
        "the two benches trading words, the managers leading the charge",
        "the dugouts have squared up — coaches nose to nose",
        "an ugly touchline row, the fourth official pleading for calm",
        "the managers have to be kept apart by their own staff",
        "the two head coaches jabbing fingers across the white line",
        "a heated exchange in the technical area, the bosses going at it",
        "the assistants wading in as the managers square up",
        "the touchline's a battleground — coaching staff trading insults",
        "the fourth official stepping between two furious managers",
        "the two bosses chest to chest on the edge of the technical area",
        "a real touchline ruck, the dugouts spilling words at each other",
        "the managers nose to nose, the fourth official trying to part them",
        "coaching staff from both camps squaring up by the boards",
        "the two technical areas have merged into one furious row",
        "the bosses jabbing fingers, faces reddening on the sideline",
        "an almighty touchline argument, staff pulling their managers back",
        "the dugouts trading barbs, the fourth official caught in the crossfire",
        "the managers up in each other's faces by the halfway line",
        "a touchline confrontation — both benches on their feet, raging",
        "the head coaches squaring up, assistants hauling them apart",
        "a venomous touchline row, fingers pointed, voices raised",
        "the two managers refusing to back down on the sideline",
        "the fourth official sandwiched between two seething dugouts",
        "coaching staff bristling, the managers leading a touchline spat",
        "the technical areas at war — bosses nose to nose, staff intervening",
        "an ill-tempered touchline row, the managers jawing at each other",
        "the dugouts squaring up, the fourth official begging for order",
        "the bosses going toe to toe right on the touchline",
        "a furious sideline confrontation between the two coaching teams",
        "the managers practically nose to nose, neither willing to relent",
        "the two head coaches striding toward each other with pure fury in their eyes",
        "a blazing row in the technical area, staff dragging their manager back",
        "the managers going at it hammer and tongs on the sideline",
        "the fourth official windmilling his arms between two furious coaches",
        "the bosses face to face, hands gesturing wildly, voices carrying into the stands",
        "a red-faced row between the two coaching teams on the touchline",
        "the rival managers standing their ground, neither taking a backward step",
        "the assistants trying to restrain their own managers on the sideline",
        "a full-blooded touchline row, the coaches absolutely apoplectic",
        "the fourth official caught between two furious teams of staff",
        "the managers squaring off like prize fighters, the touchline their ring",
        "a fierce exchange of words that the cameras absolutely love",
        "both coaching teams boiling over, the technical areas merging in fury",
        "the bosses jabbing fingers across the white line, veins bulging",
        "a raging argument between the two dugouts, nobody near calm",
        "the touchline is a warzone — both managers incandescent",
        "a venomous shouting match, the fourth official utterly overwhelmed",
        "the two managers stride toward each other, staff members hanging off their arms",
        "an almighty row at pitch side, the fourth official begging for order",
        "the managers going absolutely ballistic at one another on the touchline",
        "staff from both benches squaring up, the managers leading by example",
        "a ferocious verbal confrontation in the technical areas",
        "the two bosses absolutely livid, the fourth official looking terrified",
        "nose to nose on the sideline, assistants barely managing to hold them apart",
        "an enormous touchline row that\'s drawing the crowd to their feet",
        "the fourth official inserting himself between two furious managerial teams",
        "the managers gesticulating wildly, the words between them sharp and loud",
        "a furious dugout row that has completely overshadowed what\'s happening on the pitch",
        "both sets of staff up in each other\'s faces — the touchline has lost the plot",
    };

    /// <summary>
    /// The referee stepping in to restore order and bring the flashpoint to an end.
    /// </summary>
    private static readonly string[] RefCalmsBank =
    {
        "the referee sprinting in, arms wide, pulling them apart",
        "the captains called over to calm their players down",
        "order slowly restored, the referee reaching for his pocket",
        "the referee wading into the middle, separating the worst of it",
        "the official blowing hard on his whistle, trying to take control",
        "the referee dragging players apart one by one",
        "the captains summoned, told to get their teammates under control",
        "the referee restoring calm, notebook already in hand",
        "the official ushering players back, gradually cooling it down",
        "the referee stepping between the main protagonists",
        "calm slowly returning as the referee asserts himself",
        "the official pulling shirts apart, demanding everyone backs off",
        "the referee shepherding players away from the flashpoint",
        "the captains doing the referee's work, pulling teammates clear",
        "the official restoring order, reaching for his cards",
        "the referee in the thick of it, arms spread, keeping them apart",
        "peace gradually breaking out as the referee takes charge",
        "the official marching the worst offenders away from each other",
        "the referee blowing repeatedly, hauling the sides apart",
        "order being restored, the referee noting the names down",
        "the captains called in, instructed to calm the situation",
        "the referee separating them, finger raised in warning",
        "the official ushering everyone back to a safe distance",
        "calm slowly settling as the referee reasserts his authority",
        "the referee pulling the last few apart, reaching for his pocket",
        "the official stepping in firmly, the temperature dropping",
        "the referee corralling the players, demanding they disperse",
        "order returning at last, the referee fishing out the cards",
        "the captains dragging their men away at the referee's request",
        "the official wading through the bodies, restoring some order",
        "the referee taking names, the worst of it now subsiding",
        "calm at last, the referee marching off to dish out cards",
        "the official separating the pair, both ushered firmly apart",
        "the referee getting a grip on it, players backing away",
        "order finally restored, the referee with his cards at the ready",
        "the captains pulling rank, helping the referee cool the flames",
        "the referee planting himself between them, arms outstretched",
        "the referee sprinting over, arms spread wide, establishing himself between them",
        "the captains called in urgently to help the referee restore the peace",
        "the official blowing his whistle with real authority, the temperature dropping",
        "the referee pushing the protagonists apart with both hands",
        "order slowly trickling back as the referee asserts himself firmly",
        "the official marching in and physically separating the two main offenders",
        "the referee talking both captains down, gesturing firmly for calm",
        "the official holds them at arm\'s length, waiting for the heat to subside",
        "the referee plunging into the heart of the melee, arms outstretched",
        "calm returning at the referee\'s insistence, cards at the ready",
        "the official reaching for his yellow card while still wading through bodies",
        "the captains summoned immediately, given short, sharp instructions",
        "the referee pulling the ring-leaders apart, face stern, finger raised",
        "the official takes names in the chaos, players retreating one by one",
        "the referee gestures firmly for calm, and it slowly, grudgingly comes",
        "the official running in to defuse the situation before it worsens",
        "the captains doing sterling work, ushering teammates out of harm\'s way",
        "the referee points and shouts, and the players begin to peel apart",
        "the official restores a fragile order, notebook working overtime",
        "the captains physically pulling teammates back at the referee\'s request",
        "the referee wades through, pointing players back to their positions one by one",
        "the official establishes calm, though the cards are surely coming",
        "the referee hauls the worst two apart, standing between them until they cool",
        "order gradually asserted as the referee corrals players back to position",
        "the official reaches for his pocket and the crowd holds its breath",
        "the captains step up, talking their teams down, the referee grateful for it",
        "the referee gains control with a barrage of sharp whistle blasts",
        "the official finally manages to push through and separate the main offenders",
        "calm reasserted as the referee points emphatically for play to restart",
    };

    /// <summary>
    /// The trigger that lit the fuse for the confrontation.
    /// </summary>
    private static readonly string[] SparkBank =
    {
        "a late, nasty challenge has sparked it",
        "a stamp, an elbow, and tempers detonate",
        "a clash of heads off the ball, and now it's all going off",
        "time-wasting at the corner flag was the trigger",
        "a studs-up lunge has lit the fuse",
        "an off-the-ball shove was all it took",
        "a flailing elbow has set the whole thing off",
        "a cynical trip from behind has ignited it",
        "a stamp on the ankle, and tempers boil over instantly",
        "a wild, two-footed challenge has detonated the lot",
        "a sly dig in the ribs was the spark",
        "an over-the-top tackle has kicked it all off",
        "a shirt-pull and a face-rub, and tempers flare",
        "a kick out in frustration has lit it up",
        "a scything challenge from behind sets it ablaze",
        "an elbow into the back of the head — that's the trigger",
        "some niggle, some words, and now it's erupted",
        "a stray boot to the shins, and it's all going off",
        "provocation in the celebration was the spark",
        "a nudge off the ball, then a retaliation, and away we go",
        "a reckless slide has tipped the whole thing over",
        "a tug on the shirt that snapped someone's patience",
        "a forearm to the chin has set tempers ablaze",
        "a deliberate barge into the keeper has lit the touchpaper",
        "a flying challenge well after the ball had gone — and it's off",
        "a bit of gamesmanship has been the final straw",
        "a knee into the back, and the powder keg goes up",
        "a sly stamp away from the ball was the catalyst",
        "a needless shove in the back has triggered it all",
        "a high boot near the face has lit the fuse",
        "some afters from a 50-50, and tempers detonate",
        "a trip and a stand-over have set the whole thing alight",
        "a clattering challenge late in the move has sparked the lot",
        "a finger in the face after the whistle — and it ignites",
        "a stray arm in an aerial duel has kicked it off",
        "a niggly foul and a refusal to apologise lit the fuse",
        "a raking of the studs down the achilles — and it explodes",
        "a perceived dive has absolutely infuriated the opposition",
        "words exchanged after the goal — and now nobody\'s happy",
        "a coming-together in the air that neither side thought was accidental",
        "a deliberate stamp that only the victim and three thousand fans spotted",
        "time-wasting over the ball at the throw-in was the final straw",
        "a sly elbow in the ribs off the ball has lit the touchpaper",
        "a tug of the jersey in the wall that festered until it exploded",
        "a late, chest-high challenge that everyone in the ground could see was deliberate",
        "a standing-over of the stricken player — the worst of triggers",
        "a goal celebration right in the face of the opposition — that\'s done it",
        "a ball deliberately kicked away at a free kick has ignited tempers",
        "a clip of the heels right in front of the referee — and nothing given",
        "an off-the-ball headbutt, subtle but spotted, and chaos follows",
        "a deliberate obstruction at the corner flag was enough to detonate it",
        "a wild challenge from behind with no attempt to play the ball",
        "a string of niggly fouls building tension that finally snapped",
        "a shove from behind at a corner — wholly off the ball and totally needless",
        "a forearm smash disguised as an aerial challenge — and it\'s exploded",
        "a deliberate trip that sent someone crashing into the advertising boards",
        "a provocative celebration that crossed from triumphant into disrespectful",
        "a crude rake down the shin — no attempt to hide it",
        "a cheeky backheel on a prone player that set the whole thing alight",
        "a perceived elbow in the tunnel of play — nobody saw it, but the victim did",
        "a ball deliberately hoofed into the crowd to waste time — the spark was there",
        "a cynical block that sent a player sprawling and the benches rising",
        "an aggressive little shoulder barge at the restart — and it was on immediately",
        "a sarcastic pat on the head of a fallen opponent — that did it",
        "a vicious retaliatory foul that made everybody take two steps forward",
        "some afters after the whistle — a push here, a word there — and then it erupted",
    };

    /// <summary>
    /// Returns a fragment describing minor, almost comic pushing and chesting that fizzles out.
    /// </summary>
    /// <param name="rng">The random number generator, passed by reference.</param>
    /// <returns>A randomly selected handbags fragment.</returns>
    public static string Handbags(ref Xoshiro256 rng) => HandbagsBank[rng.NextInt(HandbagsBank.Length)];

    /// <summary>
    /// Returns a fragment describing two players squaring up nose to nose with words exchanged.
    /// </summary>
    /// <param name="rng">The random number generator, passed by reference.</param>
    /// <returns>A randomly selected face-off fragment.</returns>
    public static string FaceOff(ref Xoshiro256 rng) => FaceOffBank[rng.NextInt(FaceOffBank.Length)];

    /// <summary>
    /// Returns a fragment describing a genuine shoving match that drags players in.
    /// </summary>
    /// <param name="rng">The random number generator, passed by reference.</param>
    /// <returns>A randomly selected shoving fragment.</returns>
    public static string Shoving(ref Xoshiro256 rng) => ShovingBank[rng.NextInt(ShovingBank.Length)];

    /// <summary>
    /// Returns a fragment describing a serious, ugly brawl with many players involved.
    /// </summary>
    /// <param name="rng">The random number generator, passed by reference.</param>
    /// <returns>A randomly selected mass-confrontation fragment.</returns>
    public static string MassConfrontation(ref Xoshiro256 rng) => MassConfrontationBank[rng.NextInt(MassConfrontationBank.Length)];

    /// <summary>
    /// Returns a fragment describing the benches and staff spilling onto the pitch.
    /// </summary>
    /// <param name="rng">The random number generator, passed by reference.</param>
    /// <returns>A randomly selected bench-involved fragment.</returns>
    public static string BenchInvolved(ref Xoshiro256 rng) => BenchInvolvedBank[rng.NextInt(BenchInvolvedBank.Length)];

    /// <summary>
    /// Returns a fragment describing managers and coaching staff squaring up on the touchline.
    /// </summary>
    /// <param name="rng">The random number generator, passed by reference.</param>
    /// <returns>A randomly selected touchline-row fragment.</returns>
    public static string TouchlineRow(ref Xoshiro256 rng) => TouchlineRowBank[rng.NextInt(TouchlineRowBank.Length)];

    /// <summary>
    /// Returns a fragment describing the referee stepping in to restore order.
    /// </summary>
    /// <param name="rng">The random number generator, passed by reference.</param>
    /// <returns>A randomly selected referee-calms fragment.</returns>
    public static string RefCalms(ref Xoshiro256 rng) => RefCalmsBank[rng.NextInt(RefCalmsBank.Length)];

    /// <summary>
    /// Returns a fragment describing the trigger that lit the fuse for the confrontation.
    /// </summary>
    /// <param name="rng">The random number generator, passed by reference.</param>
    /// <returns>A randomly selected spark fragment.</returns>
    public static string Spark(ref Xoshiro256 rng) => SparkBank[rng.NextInt(SparkBank.Length)];
}
